# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\System\Setting\SettingWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingWidget(object):
    def setupUi(self, SettingWidget):
        SettingWidget.setObjectName("SettingWidget")
        SettingWidget.resize(1000, 618)
        self.gridLayout_2 = QtWidgets.QGridLayout(SettingWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pb_refresh = QtWidgets.QPushButton(SettingWidget)
        self.pb_refresh.setObjectName("pb_refresh")
        self.gridLayout_2.addWidget(self.pb_refresh, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.splitter = QtWidgets.QSplitter(SettingWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tw_setting = QtWidgets.QTreeWidget(self.splitter)
        self.tw_setting.setObjectName("tw_setting")
        self.tw_setting.headerItem().setText(0, "1")
        self.tw_setting.header().setVisible(False)
        self.sa_setting = QtWidgets.QScrollArea(self.splitter)
        self.sa_setting.setWidgetResizable(True)
        self.sa_setting.setObjectName("sa_setting")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 451, 569))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.w_setting = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.w_setting.setObjectName("w_setting")
        self.gl_setting = QtWidgets.QGridLayout(self.w_setting)
        self.gl_setting.setObjectName("gl_setting")
        self.gridLayout.addWidget(self.w_setting, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.sa_setting.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.splitter, 1, 0, 1, 2)

        self.retranslateUi(SettingWidget)
        QtCore.QMetaObject.connectSlotsByName(SettingWidget)

    def retranslateUi(self, SettingWidget):
        _translate = QtCore.QCoreApplication.translate
        SettingWidget.setWindowTitle(_translate("SettingWidget", "设置"))
        self.pb_refresh.setText(_translate("SettingWidget", "刷新"))
