# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Ui\Downloader\Downloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Downloader(object):
    def setupUi(self, Downloader):
        Downloader.setObjectName("Downloader")
        Downloader.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(Downloader)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.lw_minecraft = QtWidgets.QListWidget(Downloader)
        self.lw_minecraft.setObjectName("lw_minecraft")
        self.gridLayout.addWidget(self.lw_minecraft, 2, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(Downloader)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Downloader)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 1, 1, 1)
        self.pb_install = QtWidgets.QPushButton(Downloader)
        self.pb_install.setObjectName("pb_install")
        self.gridLayout.addWidget(self.pb_install, 0, 2, 1, 1)
        self.le_name = QtWidgets.QLineEdit(Downloader)
        self.le_name.setPlaceholderText("")
        self.le_name.setObjectName("le_name")
        self.gridLayout.addWidget(self.le_name, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(Downloader)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.lw_forge = QtWidgets.QListWidget(Downloader)
        self.lw_forge.setObjectName("lw_forge")
        self.gridLayout.addWidget(self.lw_forge, 4, 1, 1, 2)
        self.lw_fabric = QtWidgets.QListWidget(Downloader)
        self.lw_fabric.setObjectName("lw_fabric")
        self.gridLayout.addWidget(self.lw_fabric, 6, 1, 1, 2)

        self.retranslateUi(Downloader)
        QtCore.QMetaObject.connectSlotsByName(Downloader)

    def retranslateUi(self, Downloader):
        _translate = QtCore.QCoreApplication.translate
        Downloader.setWindowTitle(_translate("Downloader", "下载器"))
        self.label_2.setText(_translate("Downloader", "Forge"))
        self.label_3.setText(_translate("Downloader", "Fabric"))
        self.pb_install.setText(_translate("Downloader", "安装"))
        self.label.setText(_translate("Downloader", "Minecraft"))
