# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Functions\GameManager\LogoChooser.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogoChooser(object):
    def setupUi(self, LogoChooser):
        LogoChooser.setObjectName("LogoChooser")
        LogoChooser.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(LogoChooser)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_add = QtWidgets.QPushButton(LogoChooser)
        self.pb_add.setObjectName("pb_add")
        self.gridLayout.addWidget(self.pb_add, 1, 1, 1, 1)
        self.pb_ok = QtWidgets.QPushButton(LogoChooser)
        self.pb_ok.setObjectName("pb_ok")
        self.gridLayout.addWidget(self.pb_ok, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.lw_logos = QtWidgets.QListWidget(LogoChooser)
        self.lw_logos.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.lw_logos.setIconSize(QtCore.QSize(100, 100))
        self.lw_logos.setMovement(QtWidgets.QListView.Static)
        self.lw_logos.setResizeMode(QtWidgets.QListView.Adjust)
        self.lw_logos.setViewMode(QtWidgets.QListView.IconMode)
        self.lw_logos.setWordWrap(True)
        self.lw_logos.setObjectName("lw_logos")
        self.gridLayout.addWidget(self.lw_logos, 0, 0, 1, 3)

        self.retranslateUi(LogoChooser)
        QtCore.QMetaObject.connectSlotsByName(LogoChooser)

    def retranslateUi(self, LogoChooser):
        _translate = QtCore.QCoreApplication.translate
        LogoChooser.setWindowTitle(_translate("LogoChooser", "Logo选择"))
        self.pb_add.setText(_translate("LogoChooser", "添加"))
        self.pb_ok.setText(_translate("LogoChooser", "确定"))
