# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Ui\Update\Update.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Update(object):
    def setupUi(self, Update):
        Update.setObjectName("Update")
        Update.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(Update)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.pb_update = QtWidgets.QPushButton(Update)
        self.pb_update.setEnabled(False)
        self.pb_update.setObjectName("pb_update")
        self.gridLayout.addWidget(self.pb_update, 1, 2, 1, 1)
        self.pb_check = QtWidgets.QPushButton(Update)
        self.pb_check.setEnabled(False)
        self.pb_check.setObjectName("pb_check")
        self.gridLayout.addWidget(self.pb_check, 1, 1, 1, 1)
        self.pb_handupdate = QtWidgets.QPushButton(Update)
        self.pb_handupdate.setEnabled(False)
        self.pb_handupdate.setObjectName("pb_handupdate")
        self.gridLayout.addWidget(self.pb_handupdate, 1, 3, 1, 1)
        self.te_changelog = QtWidgets.QTextEdit(Update)
        self.te_changelog.setReadOnly(True)
        self.te_changelog.setObjectName("te_changelog")
        self.gridLayout.addWidget(self.te_changelog, 0, 0, 1, 4)

        self.retranslateUi(Update)
        QtCore.QMetaObject.connectSlotsByName(Update)

    def retranslateUi(self, Update):
        _translate = QtCore.QCoreApplication.translate
        Update.setWindowTitle(_translate("Update", "更新"))
        self.pb_update.setText(_translate("Update", "更新"))
        self.pb_check.setText(_translate("Update", "检查"))
        self.pb_handupdate.setText(_translate("Update", "手动更新"))
