# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Functions\GameDownloader\GameDownloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameDownloader(object):
    def setupUi(self, GameDownloader):
        GameDownloader.setObjectName("GameDownloader")
        GameDownloader.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(GameDownloader)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(GameDownloader)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 998, 616))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.le_name = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.le_name.setPlaceholderText("")
        self.le_name.setObjectName("le_name")
        self.gridLayout_2.addWidget(self.le_name, 0, 0, 1, 1)
        self.pb_install = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pb_install.setObjectName("pb_install")
        self.gridLayout_2.addWidget(self.pb_install, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 6, 0, 1, 1)
        self.lw_minecraft = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.lw_minecraft.setObjectName("lw_minecraft")
        self.gridLayout_2.addWidget(self.lw_minecraft, 2, 0, 1, 2)
        self.lw_forge = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.lw_forge.setObjectName("lw_forge")
        self.gridLayout_2.addWidget(self.lw_forge, 5, 0, 1, 2)
        self.lw_fabric = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.lw_fabric.setObjectName("lw_fabric")
        self.gridLayout_2.addWidget(self.lw_fabric, 7, 0, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 1, 1)

        self.retranslateUi(GameDownloader)
        QtCore.QMetaObject.connectSlotsByName(GameDownloader)

    def retranslateUi(self, GameDownloader):
        _translate = QtCore.QCoreApplication.translate
        GameDownloader.setWindowTitle(_translate("GameDownloader", "游戏下载器"))
        self.pb_install.setText(_translate("GameDownloader", "安装"))
        self.label.setText(_translate("GameDownloader", "Minecraft"))
        self.label_2.setText(_translate("GameDownloader", "Forge"))
        self.label_3.setText(_translate("GameDownloader", "Fabric"))
