# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Functions\GameDownloader\GameDownloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameDownloader(object):
    def setupUi(self, GameDownloader):
        GameDownloader.setObjectName("GameDownloader")
        GameDownloader.resize(1000, 618)
        GameDownloader.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(GameDownloader)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(GameDownloader)
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"    border:none;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1000, 618))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 8, 0, 1, 1)
        self.pb_install = PushButton(self.scrollAreaWidgetContents)
        self.pb_install.setObjectName("pb_install")
        self.gridLayout_2.addWidget(self.pb_install, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.cb_minecraft = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.cb_minecraft.setMaxVisibleItems(32)
        self.cb_minecraft.setFrame(True)
        self.cb_minecraft.setObjectName("cb_minecraft")
        self.gridLayout_2.addWidget(self.cb_minecraft, 3, 0, 1, 2)
        self.cb_fabric = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.cb_fabric.setMaxVisibleItems(32)
        self.cb_fabric.setObjectName("cb_fabric")
        self.gridLayout_2.addWidget(self.cb_fabric, 7, 0, 1, 2)
        self.cb_forge = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.cb_forge.setMaxVisibleItems(32)
        self.cb_forge.setObjectName("cb_forge")
        self.gridLayout_2.addWidget(self.cb_forge, 5, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 10, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 6, 0, 1, 1)
        self.le_name = LineEdit(self.scrollAreaWidgetContents)
        self.le_name.setPlaceholderText("")
        self.le_name.setObjectName("le_name")
        self.gridLayout_2.addWidget(self.le_name, 0, 0, 1, 1)
        self.l_warning = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.l_warning.setStyleSheet("QLabel{\n"
"    color:red;\n"
"}")
        self.l_warning.setText("")
        self.l_warning.setWordWrap(True)
        self.l_warning.setObjectName("l_warning")
        self.gridLayout_2.addWidget(self.l_warning, 1, 0, 1, 2)
        self.cb_quilt = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.cb_quilt.setObjectName("cb_quilt")
        self.gridLayout_2.addWidget(self.cb_quilt, 9, 0, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 1, 1)

        self.retranslateUi(GameDownloader)
        QtCore.QMetaObject.connectSlotsByName(GameDownloader)

    def retranslateUi(self, GameDownloader):
        _translate = QtCore.QCoreApplication.translate
        GameDownloader.setWindowTitle(_translate("GameDownloader", "游戏下载器"))
        self.label_4.setText(_translate("GameDownloader", "Quilt"))
        self.pb_install.setText(_translate("GameDownloader", "安装"))
        self.label.setText(_translate("GameDownloader", "Minecraft"))
        self.label_2.setText(_translate("GameDownloader", "Forge"))
        self.label_3.setText(_translate("GameDownloader", "Fabric"))
from qfluentwidgets import LineEdit, PushButton
