# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Functions\MusicPlayer\MusicPlayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MusicPlayer(object):
    def setupUi(self, MusicPlayer):
        MusicPlayer.setObjectName("MusicPlayer")
        MusicPlayer.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(MusicPlayer)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pb_add = TransparentToolButton(MusicPlayer)
        self.pb_add.setText("")
        self.pb_add.setObjectName("pb_add")
        self.gridLayout_2.addWidget(self.pb_add, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 5, 2, 1, 1)
        self.pb_remove = TransparentToolButton(MusicPlayer)
        self.pb_remove.setText("")
        self.pb_remove.setObjectName("pb_remove")
        self.gridLayout_2.addWidget(self.pb_remove, 1, 2, 1, 1)
        self.pb_moveup = TransparentToolButton(MusicPlayer)
        self.pb_moveup.setText("")
        self.pb_moveup.setObjectName("pb_moveup")
        self.gridLayout_2.addWidget(self.pb_moveup, 2, 2, 1, 1)
        self.pb_movedown = TransparentToolButton(MusicPlayer)
        self.pb_movedown.setText("")
        self.pb_movedown.setObjectName("pb_movedown")
        self.gridLayout_2.addWidget(self.pb_movedown, 3, 2, 1, 1)
        self.pb_movetop = TransparentToolButton(MusicPlayer)
        self.pb_movetop.setText("")
        self.pb_movetop.setObjectName("pb_movetop")
        self.gridLayout_2.addWidget(self.pb_movetop, 4, 2, 1, 1)
        self.lw_musiclist = ListWidget(MusicPlayer)
        self.lw_musiclist.setObjectName("lw_musiclist")
        self.gridLayout_2.addWidget(self.lw_musiclist, 0, 1, 6, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.l_time = QtWidgets.QLabel(MusicPlayer)
        self.l_time.setText("")
        self.l_time.setObjectName("l_time")
        self.gridLayout_3.addWidget(self.l_time, 1, 5, 1, 1)
        self.pb_control = TransparentToolButton(MusicPlayer)
        self.pb_control.setText("")
        self.pb_control.setObjectName("pb_control")
        self.gridLayout_3.addWidget(self.pb_control, 1, 0, 1, 1)
        self.pb_pre = TransparentToolButton(MusicPlayer)
        self.pb_pre.setText("")
        self.pb_pre.setObjectName("pb_pre")
        self.gridLayout_3.addWidget(self.pb_pre, 1, 1, 1, 1)
        self.hs_music = Slider(MusicPlayer)
        self.hs_music.setMaximum(0)
        self.hs_music.setOrientation(QtCore.Qt.Horizontal)
        self.hs_music.setObjectName("hs_music")
        self.gridLayout_3.addWidget(self.hs_music, 1, 4, 1, 1)
        self.pb_next = TransparentToolButton(MusicPlayer)
        self.pb_next.setText("")
        self.pb_next.setObjectName("pb_next")
        self.gridLayout_3.addWidget(self.pb_next, 1, 2, 1, 1)
        self.hs_sound = Slider(MusicPlayer)
        self.hs_sound.setMaximumSize(QtCore.QSize(128, 16777215))
        self.hs_sound.setMaximum(100)
        self.hs_sound.setProperty("value", 100)
        self.hs_sound.setOrientation(QtCore.Qt.Horizontal)
        self.hs_sound.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.hs_sound.setObjectName("hs_sound")
        self.gridLayout_3.addWidget(self.hs_sound, 1, 3, 1, 1)
        self.l_musicname = QtWidgets.QLabel(MusicPlayer)
        self.l_musicname.setText("")
        self.l_musicname.setObjectName("l_musicname")
        self.gridLayout_3.addWidget(self.l_musicname, 0, 0, 1, 5)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 2)

        self.retranslateUi(MusicPlayer)
        QtCore.QMetaObject.connectSlotsByName(MusicPlayer)

    def retranslateUi(self, MusicPlayer):
        _translate = QtCore.QCoreApplication.translate
        MusicPlayer.setWindowTitle(_translate("MusicPlayer", "音乐播放器"))
from qfluentwidgets import ListWidget, Slider, TransparentToolButton
