# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\User\PCG\FMCL\FMCL\Functions\About\AboutItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutItem(object):
    def setupUi(self, AboutItem):
        AboutItem.setObjectName("AboutItem")
        AboutItem.resize(256, 63)
        AboutItem.setWindowTitle("")
        AboutItem.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(AboutItem)
        self.gridLayout.setObjectName("gridLayout")
        self.l_desctiption = QtWidgets.QLabel(AboutItem)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.l_desctiption.setFont(font)
        self.l_desctiption.setText("")
        self.l_desctiption.setObjectName("l_desctiption")
        self.gridLayout.addWidget(self.l_desctiption, 1, 1, 1, 1)
        self.hl_operators = QtWidgets.QHBoxLayout()
        self.hl_operators.setObjectName("hl_operators")
        self.gridLayout.addLayout(self.hl_operators, 0, 3, 2, 1)
        self.l_icon = QtWidgets.QLabel(AboutItem)
        self.l_icon.setMinimumSize(QtCore.QSize(32, 32))
        self.l_icon.setMaximumSize(QtCore.QSize(32, 32))
        self.l_icon.setText("")
        self.l_icon.setObjectName("l_icon")
        self.gridLayout.addWidget(self.l_icon, 0, 0, 2, 1)
        self.l_name = QtWidgets.QLabel(AboutItem)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.l_name.setFont(font)
        self.l_name.setText("")
        self.l_name.setObjectName("l_name")
        self.gridLayout.addWidget(self.l_name, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 2, 1)

        self.retranslateUi(AboutItem)
        QtCore.QMetaObject.connectSlotsByName(AboutItem)

    def retranslateUi(self, AboutItem):
        pass
