# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Functions\About\About.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(About)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(About)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 998, 616))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gb_3rdparty = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.gb_3rdparty.setObjectName("gb_3rdparty")
        self.gl_3rdparty = QtWidgets.QGridLayout(self.gb_3rdparty)
        self.gl_3rdparty.setContentsMargins(0, 0, 0, 0)
        self.gl_3rdparty.setSpacing(0)
        self.gl_3rdparty.setObjectName("gl_3rdparty")
        self.gridLayout_2.addWidget(self.gb_3rdparty, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.gb_launcher = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.gb_launcher.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gb_launcher.setObjectName("gb_launcher")
        self.gl_launcher = QtWidgets.QGridLayout(self.gb_launcher)
        self.gl_launcher.setContentsMargins(0, 0, 0, 0)
        self.gl_launcher.setSpacing(0)
        self.gl_launcher.setObjectName("gl_launcher")
        self.gridLayout_2.addWidget(self.gb_launcher, 0, 0, 1, 1)
        self.gb_thanks = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.gb_thanks.setObjectName("gb_thanks")
        self.gl_thanks = QtWidgets.QGridLayout(self.gb_thanks)
        self.gl_thanks.setContentsMargins(0, 0, 0, 0)
        self.gl_thanks.setSpacing(0)
        self.gl_thanks.setObjectName("gl_thanks")
        self.gridLayout_2.addWidget(self.gb_thanks, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "关于"))
        self.gb_3rdparty.setTitle(_translate("About", "依赖"))
        self.gb_launcher.setTitle(_translate("About", "启动器"))
        self.gb_thanks.setTitle(_translate("About", "鸣谢"))
