# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Functions\GameManager\GameManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameManager(object):
    def setupUi(self, GameManager):
        GameManager.setObjectName("GameManager")
        GameManager.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(GameManager)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(GameManager)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 998, 616))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gb_mods = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.gb_mods.setObjectName("gb_mods")
        self.gl_mods = QtWidgets.QGridLayout(self.gb_mods)
        self.gl_mods.setObjectName("gl_mods")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gl_mods.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gl_mods.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.gb_mods, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gl_summary = QtWidgets.QGridLayout(self.groupBox)
        self.gl_summary.setObjectName("gl_summary")
        self.pb_opendirectory = QtWidgets.QPushButton(self.groupBox)
        self.pb_opendirectory.setObjectName("pb_opendirectory")
        self.gl_summary.addWidget(self.pb_opendirectory, 0, 3, 1, 1)
        self.pb_delete = QtWidgets.QPushButton(self.groupBox)
        self.pb_delete.setObjectName("pb_delete")
        self.gl_summary.addWidget(self.pb_delete, 0, 4, 1, 1)
        self.l_logo = QtWidgets.QLabel(self.groupBox)
        self.l_logo.setText("")
        self.l_logo.setObjectName("l_logo")
        self.gl_summary.addWidget(self.l_logo, 0, 0, 1, 1)
        self.le_name = QtWidgets.QLineEdit(self.groupBox)
        self.le_name.setObjectName("le_name")
        self.gl_summary.addWidget(self.le_name, 0, 1, 1, 1)
        self.pb_changelogo = QtWidgets.QPushButton(self.groupBox)
        self.pb_changelogo.setObjectName("pb_changelogo")
        self.gl_summary.addWidget(self.pb_changelogo, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gb_setting = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.gb_setting.setObjectName("gb_setting")
        self.gl_setting = QtWidgets.QGridLayout(self.gb_setting)
        self.gl_setting.setObjectName("gl_setting")
        self.gridLayout_2.addWidget(self.gb_setting, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 3, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(GameManager)
        QtCore.QMetaObject.connectSlotsByName(GameManager)

    def retranslateUi(self, GameManager):
        _translate = QtCore.QCoreApplication.translate
        GameManager.setWindowTitle(_translate("GameManager", "游戏管理"))
        self.gb_mods.setTitle(_translate("GameManager", "Mod"))
        self.groupBox.setTitle(_translate("GameManager", "概况"))
        self.pb_opendirectory.setText(_translate("GameManager", "打开文件夹"))
        self.pb_delete.setText(_translate("GameManager", "删除"))
        self.pb_changelogo.setText(_translate("GameManager", "更改图标"))
        self.gb_setting.setTitle(_translate("GameManager", "设置"))
