# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Functions\SettingEditor\SettingCards\BoolSettingCard.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BoolSettingCard(object):
    def setupUi(self, BoolSettingCard):
        BoolSettingCard.setObjectName("BoolSettingCard")
        BoolSettingCard.resize(400, 300)
        BoolSettingCard.setWindowTitle("")
        self.gridLayout = QtWidgets.QGridLayout(BoolSettingCard)
        self.gridLayout.setObjectName("gridLayout")
        self.cb_val = CheckBox(BoolSettingCard)
        self.cb_val.setText("")
        self.cb_val.setObjectName("cb_val")
        self.gridLayout.addWidget(self.cb_val, 0, 0, 1, 1)

        self.retranslateUi(BoolSettingCard)
        QtCore.QMetaObject.connectSlotsByName(BoolSettingCard)

    def retranslateUi(self, BoolSettingCard):
        pass
from qfluentwidgets import CheckBox
