# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Functions\SettingEditor\SettingCards\ColorSettingCard.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ColorSettingCard(object):
    def setupUi(self, ColorSettingCard):
        ColorSettingCard.setObjectName("ColorSettingCard")
        ColorSettingCard.resize(400, 300)
        ColorSettingCard.setWindowTitle("")
        self.gridLayout = QtWidgets.QGridLayout(ColorSettingCard)
        self.gridLayout.setObjectName("gridLayout")
        self.l_color = QtWidgets.QLabel(ColorSettingCard)
        self.l_color.setText("")
        self.l_color.setObjectName("l_color")
        self.gridLayout.addWidget(self.l_color, 0, 0, 1, 1)
        self.pb_choosecolor = PushButton(ColorSettingCard)
        self.pb_choosecolor.setObjectName("pb_choosecolor")
        self.gridLayout.addWidget(self.pb_choosecolor, 0, 1, 1, 1)

        self.retranslateUi(ColorSettingCard)
        QtCore.QMetaObject.connectSlotsByName(ColorSettingCard)

    def retranslateUi(self, ColorSettingCard):
        _translate = QtCore.QCoreApplication.translate
        self.pb_choosecolor.setText(_translate("ColorSettingCard", "选择颜色"))
from qfluentwidgets import PushButton
