# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Functions\SettingEditor\SettingCards\DictSettingCard.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DictSettingCard(object):
    def setupUi(self, DictSettingCard):
        DictSettingCard.setObjectName("DictSettingCard")
        DictSettingCard.resize(400, 300)
        DictSettingCard.setWindowTitle("")
        self.gridLayout_2 = QtWidgets.QGridLayout(DictSettingCard)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pb_add = TransparentToolButton(DictSettingCard)
        self.pb_add.setObjectName("pb_add")
        self.gridLayout_2.addWidget(self.pb_add, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.gl_elements = QtWidgets.QGridLayout()
        self.gl_elements.setObjectName("gl_elements")
        self.gridLayout_2.addLayout(self.gl_elements, 0, 0, 1, 2)

        self.retranslateUi(DictSettingCard)
        QtCore.QMetaObject.connectSlotsByName(DictSettingCard)

    def retranslateUi(self, DictSettingCard):
        pass
from qfluentwidgets import TransparentToolButton
