# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Functions\SettingEditor\SettingCards\ListSettingCardOperator.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListSettingCardOperator(object):
    def setupUi(self, ListSettingCardOperator):
        ListSettingCardOperator.setObjectName("ListSettingCardOperator")
        ListSettingCardOperator.resize(222, 300)
        ListSettingCardOperator.setMaximumSize(QtCore.QSize(16777215, 16777215))
        ListSettingCardOperator.setWindowTitle("")
        self.gridLayout = QtWidgets.QGridLayout(ListSettingCardOperator)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_movetop = TransparentToolButton(ListSettingCardOperator)
        self.pb_movetop.setObjectName("pb_movetop")
        self.gridLayout.addWidget(self.pb_movetop, 0, 3, 1, 1)
        self.pb_moveup = TransparentToolButton(ListSettingCardOperator)
        self.pb_moveup.setObjectName("pb_moveup")
        self.gridLayout.addWidget(self.pb_moveup, 0, 1, 1, 1)
        self.pb_movedown = TransparentToolButton(ListSettingCardOperator)
        self.pb_movedown.setObjectName("pb_movedown")
        self.gridLayout.addWidget(self.pb_movedown, 0, 2, 1, 1)
        self.pb_add = TransparentToolButton(ListSettingCardOperator)
        self.pb_add.setObjectName("pb_add")
        self.gridLayout.addWidget(self.pb_add, 0, 0, 1, 1)
        self.pb_delete = TransparentToolButton(ListSettingCardOperator)
        self.pb_delete.setObjectName("pb_delete")
        self.gridLayout.addWidget(self.pb_delete, 0, 4, 1, 1)

        self.retranslateUi(ListSettingCardOperator)
        QtCore.QMetaObject.connectSlotsByName(ListSettingCardOperator)

    def retranslateUi(self, ListSettingCardOperator):
        pass
from qfluentwidgets import TransparentToolButton
