# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\User\PCG\FMCL\FMCL\Functions\SettingEditor\SettingCards\ListSettingCard.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListSettingCard(object):
    def setupUi(self, ListSettingCard):
        ListSettingCard.setObjectName("ListSettingCard")
        ListSettingCard.resize(400, 300)
        ListSettingCard.setWindowTitle("")
        self._layout = QtWidgets.QGridLayout(ListSettingCard)
        self._layout.setObjectName("_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._layout.addItem(spacerItem, 1, 1, 1, 1)
        self.pb_add = TransparentToolButton(ListSettingCard)
        self.pb_add.setObjectName("pb_add")
        self._layout.addWidget(self.pb_add, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(ListSettingCard)
        self.widget.setObjectName("widget")
        self.gl_elements = QtWidgets.QGridLayout(self.widget)
        self.gl_elements.setObjectName("gl_elements")
        self._layout.addWidget(self.widget, 0, 0, 1, 2)

        self.retranslateUi(ListSettingCard)
        QtCore.QMetaObject.connectSlotsByName(ListSettingCard)

    def retranslateUi(self, ListSettingCard):
        pass
from qfluentwidgets import TransparentToolButton
