# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Functions\SettingEditor\SettingCards\StrSettingCard.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StrSettingCard(object):
    def setupUi(self, StrSettingCard):
        StrSettingCard.setObjectName("StrSettingCard")
        StrSettingCard.resize(400, 300)
        StrSettingCard.setWindowTitle("")
        self.gridLayout = QtWidgets.QGridLayout(StrSettingCard)
        self.gridLayout.setObjectName("gridLayout")
        self.le_val = LineEdit(StrSettingCard)
        self.le_val.setObjectName("le_val")
        self.gridLayout.addWidget(self.le_val, 0, 0, 1, 1)

        self.retranslateUi(StrSettingCard)
        QtCore.QMetaObject.connectSlotsByName(StrSettingCard)

    def retranslateUi(self, StrSettingCard):
        pass
from qfluentwidgets import LineEdit
