# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Functions\GameManager\NBTViewer\NBTViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NBTViewer(object):
    def setupUi(self, NBTViewer):
        NBTViewer.setObjectName("NBTViewer")
        NBTViewer.resize(1000, 618)
        self.gridLayout_2 = QtWidgets.QGridLayout(NBTViewer)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(NBTViewer)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tw_directory = TreeWidget(self.splitter)
        self.tw_directory.setColumnCount(2)
        self.tw_directory.setObjectName("tw_directory")
        self.tw_directory.headerItem().setText(0, "1")
        self.tw_directory.headerItem().setText(1, "2")
        self.tw_directory.header().setVisible(False)
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tb_viewer = TabBar(self.widget)
        self.tb_viewer.setMovable(True)
        self.tb_viewer.setScrollable(True)
        self.tb_viewer.setProperty("tabMaxWidth", 200)
        self.tb_viewer.setObjectName("tb_viewer")
        self.gridLayout.addWidget(self.tb_viewer, 0, 0, 1, 1)
        self.sw_viewer = QtWidgets.QStackedWidget(self.widget)
        self.sw_viewer.setObjectName("sw_viewer")
        self.gridLayout.addWidget(self.sw_viewer, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(NBTViewer)
        QtCore.QMetaObject.connectSlotsByName(NBTViewer)

    def retranslateUi(self, NBTViewer):
        _translate = QtCore.QCoreApplication.translate
        NBTViewer.setWindowTitle(_translate("NBTViewer", "NBT查看器"))
from qfluentwidgets import TabBar, TreeWidget
