# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\User\PCG\FMCL\FMCL\Extras\FMCL\Functions\M3U8Downloader\M3U8Downloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_M3U8Downloader(object):
    def setupUi(self, M3U8Downloader):
        M3U8Downloader.setObjectName("M3U8Downloader")
        M3U8Downloader.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(M3U8Downloader)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(M3U8Downloader)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(M3U8Downloader)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(M3U8Downloader)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.le_savepath = LineEdit(M3U8Downloader)
        self.le_savepath.setObjectName("le_savepath")
        self.gridLayout.addWidget(self.le_savepath, 3, 1, 1, 1)
        self.pb_choosepath = PushButton(M3U8Downloader)
        self.pb_choosepath.setObjectName("pb_choosepath")
        self.gridLayout.addWidget(self.pb_choosepath, 3, 2, 1, 1)
        self.le_name = LineEdit(M3U8Downloader)
        self.le_name.setObjectName("le_name")
        self.gridLayout.addWidget(self.le_name, 2, 1, 1, 2)
        self.le_url = LineEdit(M3U8Downloader)
        self.le_url.setObjectName("le_url")
        self.gridLayout.addWidget(self.le_url, 0, 1, 1, 2)
        self.pb_download = PushButton(M3U8Downloader)
        self.pb_download.setObjectName("pb_download")
        self.gridLayout.addWidget(self.pb_download, 4, 0, 1, 3)

        self.retranslateUi(M3U8Downloader)
        QtCore.QMetaObject.connectSlotsByName(M3U8Downloader)

    def retranslateUi(self, M3U8Downloader):
        _translate = QtCore.QCoreApplication.translate
        M3U8Downloader.setWindowTitle(_translate("M3U8Downloader", "M3U8下载器"))
        self.label_2.setText(_translate("M3U8Downloader", "名称"))
        self.label_3.setText(_translate("M3U8Downloader", "保存路径"))
        self.label.setText(_translate("M3U8Downloader", "网址"))
        self.pb_choosepath.setText(_translate("M3U8Downloader", "选择"))
        self.pb_download.setText(_translate("M3U8Downloader", "下载"))
from qfluentwidgets import LineEdit, PushButton
