# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Ui\Downloader\Downloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Downloader(object):
    def setupUi(self, Downloader):
        Downloader.setObjectName("Downloader")
        Downloader.resize(1000, 618)
        self.f_panel = QtWidgets.QFrame(Downloader)
        self.f_panel.setGeometry(QtCore.QRect(0, 0, 1000, 45))
        self.f_panel.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background-color:rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(229,229,229);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    border-bottom:2px solid rbg(0,0,0);\n"
"}")
        self.f_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_panel.setObjectName("f_panel")
        self.pb_minecraft = QCustomButton(self.f_panel)
        self.pb_minecraft.setGeometry(QtCore.QRect(0, 0, 64, 45))
        self.pb_minecraft.setCheckable(True)
        self.pb_minecraft.setAutoExclusive(True)
        self.pb_minecraft.setAutoDefault(False)
        self.pb_minecraft.setObjectName("pb_minecraft")
        self.pb_mod = QCustomButton(self.f_panel)
        self.pb_mod.setGeometry(QtCore.QRect(64, 0, 64, 45))
        self.pb_mod.setCheckable(True)
        self.pb_mod.setAutoExclusive(True)
        self.pb_mod.setObjectName("pb_mod")
        self.w_ui = QtWidgets.QWidget(Downloader)
        self.w_ui.setGeometry(QtCore.QRect(0, 45, 1000, 573))
        self.w_ui.setObjectName("w_ui")

        self.retranslateUi(Downloader)
        QtCore.QMetaObject.connectSlotsByName(Downloader)

    def retranslateUi(self, Downloader):
        _translate = QtCore.QCoreApplication.translate
        Downloader.setWindowTitle(_translate("Downloader", "下载"))
        self.pb_minecraft.setText(_translate("Downloader", "Minecraft"))
        self.pb_mod.setText(_translate("Downloader", "Mod"))
from Ui.QCustomButton import QCustomButton
