# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Ui\Downloader\Minecraft.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Minecraft(object):
    def setupUi(self, Minecraft):
        Minecraft.setObjectName("Minecraft")
        Minecraft.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(Minecraft)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Minecraft)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.le_name = QtWidgets.QLineEdit(self.groupBox)
        self.le_name.setObjectName("le_name")
        self.gridLayout_2.addWidget(self.le_name, 0, 0, 1, 1)
        self.pb_install = QtWidgets.QPushButton(self.groupBox)
        self.pb_install.setObjectName("pb_install")
        self.gridLayout_2.addWidget(self.pb_install, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Minecraft)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.cb_forge = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_forge.setObjectName("cb_forge")
        self.gridLayout_3.addWidget(self.cb_forge, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.cb_minecraft = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_minecraft.setObjectName("cb_minecraft")
        self.gridLayout_3.addWidget(self.cb_minecraft, 0, 1, 1, 1)
        self.cb_liteloader = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_liteloader.setObjectName("cb_liteloader")
        self.gridLayout_3.addWidget(self.cb_liteloader, 3, 1, 1, 1)
        self.cb_optifine = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_optifine.setObjectName("cb_optifine")
        self.gridLayout_3.addWidget(self.cb_optifine, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)

        self.retranslateUi(Minecraft)
        QtCore.QMetaObject.connectSlotsByName(Minecraft)

    def retranslateUi(self, Minecraft):
        _translate = QtCore.QCoreApplication.translate
        Minecraft.setWindowTitle(_translate("Minecraft", "Minecraft"))
        self.groupBox.setTitle(_translate("Minecraft", "下载信息"))
        self.pb_install.setText(_translate("Minecraft", "安装"))
        self.groupBox_2.setTitle(_translate("Minecraft", "下载内容"))
        self.label.setText(_translate("Minecraft", "Forge"))
        self.label_4.setText(_translate("Minecraft", "Liteloader"))
        self.label_5.setText(_translate("Minecraft", "Minecraft"))
        self.label_3.setText(_translate("Minecraft", "Optifine"))
