# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Ui\Downloader\ModDetail.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModDetail(object):
    def setupUi(self, ModDetail):
        ModDetail.setObjectName("ModDetail")
        ModDetail.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(ModDetail)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(ModDetail)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.l_title = QtWidgets.QLabel(self.groupBox)
        self.l_title.setText("")
        self.l_title.setObjectName("l_title")
        self.gridLayout_2.addWidget(self.l_title, 0, 0, 1, 2)
        self.l_describe = QtWidgets.QLabel(self.groupBox)
        self.l_describe.setText("")
        self.l_describe.setObjectName("l_describe")
        self.gridLayout_2.addWidget(self.l_describe, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(ModDetail)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 960, 494))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tb_modfiles = QtWidgets.QToolBox(self.scrollAreaWidgetContents)
        self.tb_modfiles.setObjectName("tb_modfiles")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setGeometry(QtCore.QRect(0, 0, 942, 450))
        self.page_1.setObjectName("page_1")
        self.tb_modfiles.addItem(self.page_1, "")
        self.gridLayout_4.addWidget(self.tb_modfiles, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)

        self.retranslateUi(ModDetail)
        self.tb_modfiles.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ModDetail)

    def retranslateUi(self, ModDetail):
        _translate = QtCore.QCoreApplication.translate
        ModDetail.setWindowTitle(_translate("ModDetail", "Mod细节"))
        self.groupBox.setTitle(_translate("ModDetail", "信息"))
        self.groupBox_2.setTitle(_translate("ModDetail", "Mod文件"))
        self.tb_modfiles.setItemText(self.tb_modfiles.indexOf(self.page_1), _translate("ModDetail", "前置Mod"))
