# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Ui\Downloader\Mods.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mods(object):
    def setupUi(self, Mods):
        Mods.setObjectName("Mods")
        Mods.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(Mods)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Mods)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.le_search = QtWidgets.QLineEdit(self.groupBox)
        self.le_search.setObjectName("le_search")
        self.gridLayout_2.addWidget(self.le_search, 0, 0, 1, 1)
        self.pb_search = QtWidgets.QPushButton(self.groupBox)
        self.pb_search.setObjectName("pb_search")
        self.gridLayout_2.addWidget(self.pb_search, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.lw_result = QtWidgets.QListWidget(Mods)
        self.lw_result.setObjectName("lw_result")
        self.gridLayout.addWidget(self.lw_result, 1, 0, 1, 1)

        self.retranslateUi(Mods)
        QtCore.QMetaObject.connectSlotsByName(Mods)

    def retranslateUi(self, Mods):
        _translate = QtCore.QCoreApplication.translate
        Mods.setWindowTitle(_translate("Mods", "Mods"))
        self.groupBox.setTitle(_translate("Mods", "搜索"))
        self.pb_search.setText(_translate("Mods", "搜索"))
