# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Ui\News\NewsInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewsInfo(object):
    def setupUi(self, NewsInfo):
        NewsInfo.setObjectName("NewsInfo")
        NewsInfo.resize(256, 256)
        self.gridLayout = QtWidgets.QGridLayout(NewsInfo)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.l_image = QtWidgets.QLabel(NewsInfo)
        self.l_image.setText("")
        self.l_image.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.l_image.setObjectName("l_image")
        self.gridLayout.addWidget(self.l_image, 0, 0, 1, 1)

        self.retranslateUi(NewsInfo)
        QtCore.QMetaObject.connectSlotsByName(NewsInfo)

    def retranslateUi(self, NewsInfo):
        _translate = QtCore.QCoreApplication.translate
        NewsInfo.setWindowTitle(_translate("NewsInfo", "新闻信息"))
