# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Help\Developer\CustomFunction.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomFunction(object):
    def setupUi(self, CustomFunction):
        CustomFunction.setObjectName("CustomFunction")
        CustomFunction.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(CustomFunction)
        self.gridLayout.setObjectName("gridLayout")
        self.ScrollArea = ScrollArea(CustomFunction)
        self.ScrollArea.setStyleSheet("QScrollArea{\n"
"    border:none;\n"
"}")
        self.ScrollArea.setWidgetResizable(True)
        self.ScrollArea.setObjectName("ScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 982, 1296))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.BodyLabel = BodyLabel(self.scrollAreaWidgetContents)
        self.BodyLabel.setWordWrap(True)
        self.BodyLabel.setProperty("lightColor", QtGui.QColor(255, 0, 0))
        self.BodyLabel.setObjectName("BodyLabel")
        self.gridLayout_2.addWidget(self.BodyLabel, 0, 0, 1, 1)
        self.BodyLabel_19 = BodyLabel(self.scrollAreaWidgetContents)
        self.BodyLabel_19.setWordWrap(True)
        self.BodyLabel_19.setProperty("lightColor", QtGui.QColor(0, 0, 255))
        self.BodyLabel_19.setObjectName("BodyLabel_19")
        self.gridLayout_2.addWidget(self.BodyLabel_19, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 6, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.BodyLabel_17 = BodyLabel(self.groupBox_7)
        self.BodyLabel_17.setWordWrap(True)
        self.BodyLabel_17.setObjectName("BodyLabel_17")
        self.gridLayout_9.addWidget(self.BodyLabel_17, 0, 0, 1, 1)
        self.BodyLabel_22 = BodyLabel(self.groupBox_7)
        self.BodyLabel_22.setWordWrap(True)
        self.BodyLabel_22.setObjectName("BodyLabel_22")
        self.gridLayout_9.addWidget(self.BodyLabel_22, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_7, 3, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.BodyLabel_2 = BodyLabel(self.groupBox)
        self.BodyLabel_2.setWordWrap(True)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.gridLayout_3.addWidget(self.BodyLabel_2, 0, 0, 1, 1)
        self.BodyLabel_3 = BodyLabel(self.groupBox)
        self.BodyLabel_3.setWordWrap(True)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.gridLayout_3.addWidget(self.BodyLabel_3, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.BodyLabel_11 = BodyLabel(self.groupBox_5)
        self.BodyLabel_11.setWordWrap(True)
        self.BodyLabel_11.setObjectName("BodyLabel_11")
        self.gridLayout_7.addWidget(self.BodyLabel_11, 1, 0, 1, 1)
        self.BodyLabel_10 = BodyLabel(self.groupBox_5)
        self.BodyLabel_10.setWordWrap(True)
        self.BodyLabel_10.setObjectName("BodyLabel_10")
        self.gridLayout_7.addWidget(self.BodyLabel_10, 0, 0, 1, 1)
        self.BodyLabel_12 = BodyLabel(self.groupBox_5)
        self.BodyLabel_12.setWordWrap(True)
        self.BodyLabel_12.setObjectName("BodyLabel_12")
        self.gridLayout_7.addWidget(self.BodyLabel_12, 3, 0, 1, 1)
        self.TextEdit_3 = TextEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextEdit_3.sizePolicy().hasHeightForWidth())
        self.TextEdit_3.setSizePolicy(sizePolicy)
        self.TextEdit_3.setMinimumSize(QtCore.QSize(0, 100))
        self.TextEdit_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.TextEdit_3.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.TextEdit_3.setReadOnly(True)
        self.TextEdit_3.setOverwriteMode(False)
        self.TextEdit_3.setObjectName("TextEdit_3")
        self.gridLayout_7.addWidget(self.TextEdit_3, 2, 0, 1, 1)
        self.BodyLabel_13 = BodyLabel(self.groupBox_5)
        self.BodyLabel_13.setWordWrap(True)
        self.BodyLabel_13.setObjectName("BodyLabel_13")
        self.gridLayout_7.addWidget(self.BodyLabel_13, 4, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 3, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.TextEdit_2 = TextEdit(self.groupBox_4)
        self.TextEdit_2.setMinimumSize(QtCore.QSize(0, 52))
        self.TextEdit_2.setMaximumSize(QtCore.QSize(16777215, 52))
        self.TextEdit_2.setReadOnly(True)
        self.TextEdit_2.setObjectName("TextEdit_2")
        self.gridLayout_6.addWidget(self.TextEdit_2, 2, 0, 1, 1)
        self.BodyLabel_7 = BodyLabel(self.groupBox_4)
        self.BodyLabel_7.setWordWrap(True)
        self.BodyLabel_7.setObjectName("BodyLabel_7")
        self.gridLayout_6.addWidget(self.BodyLabel_7, 0, 0, 1, 1)
        self.BodyLabel_8 = BodyLabel(self.groupBox_4)
        self.BodyLabel_8.setWordWrap(True)
        self.BodyLabel_8.setObjectName("BodyLabel_8")
        self.gridLayout_6.addWidget(self.BodyLabel_8, 1, 0, 1, 1)
        self.BodyLabel_9 = BodyLabel(self.groupBox_4)
        self.BodyLabel_9.setWordWrap(True)
        self.BodyLabel_9.setObjectName("BodyLabel_9")
        self.gridLayout_6.addWidget(self.BodyLabel_9, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.TextEdit = TextEdit(self.groupBox_3)
        self.TextEdit.setMinimumSize(QtCore.QSize(0, 60))
        self.TextEdit.setMaximumSize(QtCore.QSize(16777215, 60))
        self.TextEdit.setReadOnly(True)
        self.TextEdit.setObjectName("TextEdit")
        self.gridLayout_5.addWidget(self.TextEdit, 2, 0, 1, 1)
        self.BodyLabel_4 = BodyLabel(self.groupBox_3)
        self.BodyLabel_4.setWordWrap(True)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.gridLayout_5.addWidget(self.BodyLabel_4, 0, 0, 1, 1)
        self.BodyLabel_5 = BodyLabel(self.groupBox_3)
        self.BodyLabel_5.setWordWrap(True)
        self.BodyLabel_5.setObjectName("BodyLabel_5")
        self.gridLayout_5.addWidget(self.BodyLabel_5, 1, 0, 1, 1)
        self.BodyLabel_6 = BodyLabel(self.groupBox_3)
        self.BodyLabel_6.setWordWrap(True)
        self.BodyLabel_6.setObjectName("BodyLabel_6")
        self.gridLayout_5.addWidget(self.BodyLabel_6, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.BodyLabel_15 = BodyLabel(self.groupBox_6)
        self.BodyLabel_15.setWordWrap(True)
        self.BodyLabel_15.setObjectName("BodyLabel_15")
        self.gridLayout_8.addWidget(self.BodyLabel_15, 1, 0, 1, 1)
        self.TextEdit_4 = TextEdit(self.groupBox_6)
        self.TextEdit_4.setMinimumSize(QtCore.QSize(0, 180))
        self.TextEdit_4.setMaximumSize(QtCore.QSize(16777215, 180))
        self.TextEdit_4.setObjectName("TextEdit_4")
        self.gridLayout_8.addWidget(self.TextEdit_4, 2, 0, 1, 1)
        self.BodyLabel_14 = BodyLabel(self.groupBox_6)
        self.BodyLabel_14.setWordWrap(True)
        self.BodyLabel_14.setObjectName("BodyLabel_14")
        self.gridLayout_8.addWidget(self.BodyLabel_14, 0, 0, 1, 1)
        self.BodyLabel_16 = BodyLabel(self.groupBox_6)
        self.BodyLabel_16.setWordWrap(True)
        self.BodyLabel_16.setObjectName("BodyLabel_16")
        self.gridLayout_8.addWidget(self.BodyLabel_16, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_6, 4, 0, 1, 1)
        self.BodyLabel_18 = BodyLabel(self.groupBox_2)
        self.BodyLabel_18.setWordWrap(True)
        self.BodyLabel_18.setObjectName("BodyLabel_18")
        self.gridLayout_4.addWidget(self.BodyLabel_18, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.BodyLabel_20 = BodyLabel(self.groupBox_8)
        self.BodyLabel_20.setWordWrap(True)
        self.BodyLabel_20.setObjectName("BodyLabel_20")
        self.gridLayout_10.addWidget(self.BodyLabel_20, 0, 0, 1, 1)
        self.BodyLabel_21 = BodyLabel(self.groupBox_8)
        self.BodyLabel_21.setWordWrap(True)
        self.BodyLabel_21.setObjectName("BodyLabel_21")
        self.gridLayout_10.addWidget(self.BodyLabel_21, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_8, 4, 0, 1, 1)
        self.ScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.ScrollArea, 0, 0, 1, 1)

        self.retranslateUi(CustomFunction)
        QtCore.QMetaObject.connectSlotsByName(CustomFunction)

    def retranslateUi(self, CustomFunction):
        _translate = QtCore.QCoreApplication.translate
        CustomFunction.setWindowTitle(_translate("CustomFunction", "自定义功能"))
        self.BodyLabel.setText(_translate("CustomFunction", "请先看完\"开发者\"帮助后再看本页面"))
        self.BodyLabel_19.setText(_translate("CustomFunction", "如果有不清楚的可以去FMCL/Functions或FMCL/Default/FMCL/Functions下看看已有的功能是如何实现的"))
        self.groupBox_7.setTitle(_translate("CustomFunction", "步骤3：编写功能"))
        self.BodyLabel_17.setText(_translate("CustomFunction", "准备工作已做完，可以开始进行真正的功能开发了"))
        self.BodyLabel_22.setText(_translate("CustomFunction", "实际上步骤2和步骤3不一定要依次进行"))
        self.groupBox.setTitle(_translate("CustomFunction", "步骤1：创建功能"))
        self.BodyLabel_2.setText(_translate("CustomFunction", "在FMCL/Functions中创建文件夹，文件夹名称自取"))
        self.BodyLabel_3.setText(_translate("CustomFunction", "在该文件夹下创建__init__.py"))
        self.groupBox_2.setTitle(_translate("CustomFunction", "步骤2：编写对外函数"))
        self.groupBox_5.setTitle(_translate("CustomFunction", "defaultSetting和defaultSettingAttr"))
        self.BodyLabel_11.setText(_translate("CustomFunction", "以下是这两个函数的基本模板"))
        self.BodyLabel_10.setText(_translate("CustomFunction", "该功能的设置和设置属性"))
        self.BodyLabel_12.setText(_translate("CustomFunction", "对于每个设置中的每个子项都必须要有对应的属性"))
        self.TextEdit_3.setHtml(_translate("CustomFunction", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\',\'Microsoft YaHei\',\'PingFang SC\'; font-size:14px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:19px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#af00db;\">from</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\"> </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#267f99;\">Setting</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\"> </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#af00db;\">import</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\"> </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#267f99;\">SettingAttr</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#0000ff;\">def</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\"> </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#795e26;\">defaultSetting</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">():</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">    </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#af00db;\">return</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\"> {}</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#0000ff;\">def</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\"> </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#795e26;\">defaultSettingAttr</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">() -&gt; </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#267f99;\">dict</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">[</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#267f99;\">str</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">, </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#267f99;\">SettingAttr</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">]:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">    </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#af00db;\">return</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\"> {}</span></p></body></html>"))
        self.BodyLabel_13.setText(_translate("CustomFunction", "比如对于a.b.c，必须要有a, a.b, a.b.c的设置属性"))
        self.groupBox_4.setTitle(_translate("CustomFunction", "functionInfo"))
        self.TextEdit_2.setHtml(_translate("CustomFunction", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\',\'Microsoft YaHei\',\'PingFang SC\'; font-size:14px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:19px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#0000ff;\">def</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\"> </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#795e26;\">functionInfo</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">():</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">    </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#af00db;\">return</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\"> {</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#a31515;\">&quot;name&quot;</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">: </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#a31515;\">&quot;功能的名称&quot;</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">, </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#a31515;\">&quot;id&quot;</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">: </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#a31515;\">&quot;功能的标识符&quot;</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">, </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#a31515;\">&quot;icon&quot;</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">: </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#a31515;\">&quot;功能的图标&quot;</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">}</span></p></body></html>"))
        self.BodyLabel_7.setText(_translate("CustomFunction", "系统获取该功能的信息时调用"))
        self.BodyLabel_8.setText(_translate("CustomFunction", "以下是该函数的基本模板"))
        self.BodyLabel_9.setText(_translate("CustomFunction", "上面的模板返回的是完整的信息，如果有缺少，缺少的信息会由系统设置"))
        self.groupBox_3.setTitle(_translate("CustomFunction", "main"))
        self.TextEdit.setHtml(_translate("CustomFunction", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\',\'Microsoft YaHei\',\'PingFang SC\'; font-size:14px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:19px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#0000ff;\">def</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\"> </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#795e26;\">main</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">():</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">    ...</span></p></body></html>"))
        self.BodyLabel_4.setText(_translate("CustomFunction", "主程序，系统运行该功能时会调用"))
        self.BodyLabel_5.setText(_translate("CustomFunction", "以下是该函数的基本模板"))
        self.BodyLabel_6.setText(_translate("CustomFunction", "可以有任意参数，但要注意该函数调用时不一定会有参数传进来"))
        self.groupBox_6.setTitle(_translate("CustomFunction", "helpIndex"))
        self.BodyLabel_15.setText(_translate("CustomFunction", "以下是该函数的基本模板"))
        self.TextEdit_4.setHtml(_translate("CustomFunction", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\',\'Microsoft YaHei\',\'PingFang SC\'; font-size:14px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:19px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#0000ff;\">def</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\"> </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#795e26;\">helpIndex</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">():</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">    </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#af00db;\">return</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\"> {</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">        </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#a31515;\">&quot;页面1&quot;</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">: {</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">            </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#a31515;\">&quot;name&quot;</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">: </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#a31515;\">&quot;名称&quot;</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">            </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#a31515;\">&quot;page&quot;</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">: ..., </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#00821a;\">#&quot;对应的页面(可选)，是一个返回QWidget的函数</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">            </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#a31515;\">&quot;子页面1&quot;</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">: {...},</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">            </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#a31515;\">&quot;子页面2&quot;</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">: {...},</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">        },</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">        </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#a31515;\">&quot;页面2&quot;</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">: {...},</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; color:#3b3b3b;\">    }</span></p></body></html>"))
        self.BodyLabel_14.setText(_translate("CustomFunction", "该功能的帮助索引"))
        self.BodyLabel_16.setText(_translate("CustomFunction", "每个页面的字典的内容相同，并且该字典的每个键用\'.\'相连就成了标识符(id)，可以通过id直接获得对应字典的值"))
        self.BodyLabel_18.setText(_translate("CustomFunction", "以下函数都是写在__init__.py中的"))
        self.groupBox_8.setTitle(_translate("CustomFunction", "步骤4：翻译"))
        self.BodyLabel_20.setText(_translate("CustomFunction", "使用PyQt5对应的工具生成功能的翻译.ts文件，并用\"语言家\"进行翻译，翻译文件应该放在\"FMCL/Functions/你创建的文件夹/Translations\"下"))
        self.BodyLabel_21.setText(_translate("CustomFunction", "翻译文件名必须与语言类型相同，比如简体中文的翻译的文件名是\"简体中文.ts\"，英文的翻译的文件名是\"English.ts\""))
from qfluentwidgets import BodyLabel, ScrollArea, TextEdit
