# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Help\Developer\CustomHelp.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomHelp(object):
    def setupUi(self, CustomHelp):
        CustomHelp.setObjectName("CustomHelp")
        CustomHelp.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(CustomHelp)
        self.gridLayout.setObjectName("gridLayout")
        self.ScrollArea = ScrollArea(CustomHelp)
        self.ScrollArea.setStyleSheet("QScrollArea{\n"
"    border:none;\n"
"}")
        self.ScrollArea.setWidgetResizable(True)
        self.ScrollArea.setObjectName("ScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 982, 600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.BodyLabel_2 = BodyLabel(self.groupBox)
        self.BodyLabel_2.setWordWrap(True)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.gridLayout_3.addWidget(self.BodyLabel_2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 5, 0, 1, 1)
        self.BodyLabel = BodyLabel(self.scrollAreaWidgetContents)
        self.BodyLabel.setWordWrap(True)
        self.BodyLabel.setProperty("lightColor", QtGui.QColor(255, 0, 0))
        self.BodyLabel.setObjectName("BodyLabel")
        self.gridLayout_2.addWidget(self.BodyLabel, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.BodyLabel_4 = BodyLabel(self.groupBox_3)
        self.BodyLabel_4.setWordWrap(True)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.gridLayout_5.addWidget(self.BodyLabel_4, 0, 0, 1, 1)
        self.BodyLabel_5 = BodyLabel(self.groupBox_3)
        self.BodyLabel_5.setWordWrap(True)
        self.BodyLabel_5.setObjectName("BodyLabel_5")
        self.gridLayout_5.addWidget(self.BodyLabel_5, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 3, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.BodyLabel_3 = BodyLabel(self.groupBox_2)
        self.BodyLabel_3.setWordWrap(True)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.gridLayout_4.addWidget(self.BodyLabel_3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.BodyLabel_6 = BodyLabel(self.groupBox_4)
        self.BodyLabel_6.setWordWrap(True)
        self.BodyLabel_6.setObjectName("BodyLabel_6")
        self.gridLayout_6.addWidget(self.BodyLabel_6, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 4, 0, 1, 1)
        self.ScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.ScrollArea, 0, 0, 1, 1)

        self.retranslateUi(CustomHelp)
        QtCore.QMetaObject.connectSlotsByName(CustomHelp)

    def retranslateUi(self, CustomHelp):
        _translate = QtCore.QCoreApplication.translate
        CustomHelp.setWindowTitle(_translate("CustomHelp", "自定义帮助"))
        self.groupBox.setTitle(_translate("CustomHelp", "步骤1：创建帮助"))
        self.BodyLabel_2.setText(_translate("CustomHelp", "在FMCL/Help文件夹下创建文件夹，文件夹名称自取，并创建__init__.py"))
        self.BodyLabel.setText(_translate("CustomHelp", "请先看完\"开发者\"帮助后再看本页面"))
        self.groupBox_3.setTitle(_translate("CustomHelp", "步骤3：编写帮助页面"))
        self.BodyLabel_4.setText(_translate("CustomHelp", "准备工作已做完，可以开始编写具体的帮助页面了"))
        self.BodyLabel_5.setText(_translate("CustomHelp", "实际上步骤2和步骤3不一定要依次进行"))
        self.groupBox_2.setTitle(_translate("CustomHelp", "步骤2：编写对外函数"))
        self.BodyLabel_3.setText(_translate("CustomHelp", "只需在__init__.py中写helpIndex函数即可，该函数内容与\"自定义功能\"中提到的helpIndex函数相同"))
        self.groupBox_4.setTitle(_translate("CustomHelp", "步骤4：翻译"))
        self.BodyLabel_6.setText(_translate("CustomHelp", "同\"自定义功能\"步骤4，但要注意的是翻译文件要放在\"FMCL/Help/你创建的文件夹/Translations\"下"))
from qfluentwidgets import BodyLabel, ScrollArea
