# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Help\Developer\Developer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Developer(object):
    def setupUi(self, Developer):
        Developer.setObjectName("Developer")
        Developer.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(Developer)
        self.gridLayout.setObjectName("gridLayout")
        self.ScrollArea = ScrollArea(Developer)
        self.ScrollArea.setStyleSheet("QScrollArea{\n"
"    border:none;\n"
"}")
        self.ScrollArea.setWidgetResizable(True)
        self.ScrollArea.setObjectName("ScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 982, 600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.BodyLabel = BodyLabel(self.scrollAreaWidgetContents)
        self.BodyLabel.setWordWrap(True)
        self.BodyLabel.setObjectName("BodyLabel")
        self.gridLayout_2.addWidget(self.BodyLabel, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.BodyLabel_3 = BodyLabel(self.groupBox)
        self.BodyLabel_3.setWordWrap(True)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.gridLayout_3.addWidget(self.BodyLabel_3, 0, 0, 1, 1)
        self.BodyLabel_2 = BodyLabel(self.groupBox)
        self.BodyLabel_2.setWordWrap(True)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.gridLayout_3.addWidget(self.BodyLabel_2, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.BodyLabel_4 = BodyLabel(self.scrollAreaWidgetContents)
        self.BodyLabel_4.setWordWrap(True)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.gridLayout_2.addWidget(self.BodyLabel_4, 2, 0, 1, 1)
        self.ScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.ScrollArea, 0, 0, 1, 1)

        self.retranslateUi(Developer)
        QtCore.QMetaObject.connectSlotsByName(Developer)

    def retranslateUi(self, Developer):
        _translate = QtCore.QCoreApplication.translate
        Developer.setWindowTitle(_translate("Developer", "开发者"))
        self.BodyLabel.setText(_translate("Developer", "此帮助页面及其子帮助页面是面向开发者的"))
        self.groupBox.setTitle(_translate("Developer", "对开发者的基本要求"))
        self.BodyLabel_3.setText(_translate("Developer", "1. 会Python"))
        self.BodyLabel_2.setText(_translate("Developer", "2. 会PyQt5"))
        self.BodyLabel_4.setText(_translate("Developer", "无特殊说明，该帮助页面及其子页面中提到的路径都是以启动器主程序所在目录为根目录"))
from qfluentwidgets import BodyLabel, ScrollArea
