# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Functions\StrongholdFinder\HowToGetData.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HowToGetData(object):
    def setupUi(self, HowToGetData):
        HowToGetData.setObjectName("HowToGetData")
        HowToGetData.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(HowToGetData)
        self.gridLayout.setObjectName("gridLayout")
        self.ScrollArea = ScrollArea(HowToGetData)
        self.ScrollArea.setStyleSheet("QScrollArea{\n"
"    border:none;\n"
"}")
        self.ScrollArea.setWidgetResizable(True)
        self.ScrollArea.setObjectName("ScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 982, 600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.BodyLabel_5 = BodyLabel(self.scrollAreaWidgetContents)
        self.BodyLabel_5.setWordWrap(True)
        self.BodyLabel_5.setObjectName("BodyLabel_5")
        self.gridLayout_2.addWidget(self.BodyLabel_5, 4, 0, 1, 1)
        self.BodyLabel_4 = BodyLabel(self.scrollAreaWidgetContents)
        self.BodyLabel_4.setWordWrap(True)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.gridLayout_2.addWidget(self.BodyLabel_4, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 404, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 7, 0, 1, 1)
        self.BodyLabel_3 = BodyLabel(self.scrollAreaWidgetContents)
        self.BodyLabel_3.setWordWrap(True)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.gridLayout_2.addWidget(self.BodyLabel_3, 2, 0, 1, 1)
        self.BodyLabel_6 = BodyLabel(self.scrollAreaWidgetContents)
        self.BodyLabel_6.setWordWrap(True)
        self.BodyLabel_6.setObjectName("BodyLabel_6")
        self.gridLayout_2.addWidget(self.BodyLabel_6, 5, 0, 1, 1)
        self.BodyLabel = BodyLabel(self.scrollAreaWidgetContents)
        self.BodyLabel.setWordWrap(True)
        self.BodyLabel.setObjectName("BodyLabel")
        self.gridLayout_2.addWidget(self.BodyLabel, 0, 0, 1, 1)
        self.BodyLabel_2 = BodyLabel(self.scrollAreaWidgetContents)
        self.BodyLabel_2.setWordWrap(True)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.gridLayout_2.addWidget(self.BodyLabel_2, 1, 0, 1, 1)
        self.BodyLabel_7 = BodyLabel(self.scrollAreaWidgetContents)
        self.BodyLabel_7.setWordWrap(True)
        self.BodyLabel_7.setObjectName("BodyLabel_7")
        self.gridLayout_2.addWidget(self.BodyLabel_7, 6, 0, 1, 1)
        self.ScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.ScrollArea, 0, 0, 1, 1)

        self.retranslateUi(HowToGetData)
        QtCore.QMetaObject.connectSlotsByName(HowToGetData)

    def retranslateUi(self, HowToGetData):
        _translate = QtCore.QCoreApplication.translate
        HowToGetData.setWindowTitle(_translate("HowToGetData", "如何获取数据"))
        self.BodyLabel_5.setText(_translate("HowToGetData", "5.将这两组数据填入对应位置"))
        self.BodyLabel_4.setText(_translate("HowToGetData", "4.重复步骤2和3,获得两组数据"))
        self.BodyLabel_3.setText(_translate("HowToGetData", "3.以当前方向为基准横向走动约几百米"))
        self.BodyLabel_6.setText(_translate("HowToGetData", "6.点击\"计算\"按钮"))
        self.BodyLabel.setText(_translate("HowToGetData", "1.按F3打开调试屏幕。"))
        self.BodyLabel_2.setText(_translate("HowToGetData", "2.使用末影之眼，准星指向末影之眼悬停处，填写人物调试屏幕上的X坐标、Z坐标和当前角度"))
        self.BodyLabel_7.setText(_translate("HowToGetData", "7.完成"))
from qfluentwidgets import BodyLabel, ScrollArea
