# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'News.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_News(object):
    def setupUi(self, News):
        News.setObjectName("News")
        News.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(News)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = ScrollArea(News)
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"    border:none;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1000, 618))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gl_scrollarea = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gl_scrollarea.setContentsMargins(0, 0, 0, 0)
        self.gl_scrollarea.setObjectName("gl_scrollarea")
        self.gl_news = QtWidgets.QGridLayout()
        self.gl_news.setObjectName("gl_news")
        self.gl_scrollarea.addLayout(self.gl_news, 0, 0, 1, 1)
        self.pb_loadmore = PushButton(self.scrollAreaWidgetContents)
        self.pb_loadmore.setObjectName("pb_loadmore")
        self.gl_scrollarea.addWidget(self.pb_loadmore, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(News)
        QtCore.QMetaObject.connectSlotsByName(News)

    def retranslateUi(self, News):
        _translate = QtCore.QCoreApplication.translate
        News.setWindowTitle(_translate("News", "新闻"))
        self.pb_loadmore.setText(_translate("News", "加载更多内容"))
from qfluentwidgets import PushButton, ScrollArea
