# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Ui\User\NewUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewUser(object):
    def setupUi(self, NewUser):
        NewUser.setObjectName("NewUser")
        NewUser.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(NewUser)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(NewUser)
        self.tabWidget.setObjectName("tabWidget")
        self.offline = QtWidgets.QWidget()
        self.offline.setObjectName("offline")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.offline)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.le_offline_name = QtWidgets.QLineEdit(self.offline)
        self.le_offline_name.setObjectName("le_offline_name")
        self.gridLayout_2.addWidget(self.le_offline_name, 0, 0, 1, 1)
        self.tabWidget.addTab(self.offline, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.pb_cancel = QtWidgets.QPushButton(NewUser)
        self.pb_cancel.setObjectName("pb_cancel")
        self.gridLayout.addWidget(self.pb_cancel, 2, 2, 1, 1)
        self.pb_ok = QtWidgets.QPushButton(NewUser)
        self.pb_ok.setObjectName("pb_ok")
        self.gridLayout.addWidget(self.pb_ok, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)

        self.retranslateUi(NewUser)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NewUser)

    def retranslateUi(self, NewUser):
        _translate = QtCore.QCoreApplication.translate
        NewUser.setWindowTitle(_translate("NewUser", "新用户"))
        self.le_offline_name.setPlaceholderText(_translate("NewUser", "请输入用户名"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.offline), _translate("NewUser", "离线登录"))
        self.pb_cancel.setText(_translate("NewUser", "取消"))
        self.pb_ok.setText(_translate("NewUser", "确定"))
