# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Ui\User\User.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_User(object):
    def setupUi(self, User):
        User.setObjectName("User")
        User.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(User)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_add = QtWidgets.QPushButton(User)
        self.pb_add.setText("")
        self.pb_add.setObjectName("pb_add")
        self.gridLayout.addWidget(self.pb_add, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.lw_users = QtWidgets.QListWidget(User)
        self.lw_users.setObjectName("lw_users")
        self.gridLayout.addWidget(self.lw_users, 0, 0, 1, 2)

        self.retranslateUi(User)
        QtCore.QMetaObject.connectSlotsByName(User)

    def retranslateUi(self, User):
        _translate = QtCore.QCoreApplication.translate
        User.setWindowTitle(_translate("User", "用户"))
