# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Functions\GameManager\SaveManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveManager(object):
    def setupUi(self, SaveManager):
        SaveManager.setObjectName("SaveManager")
        SaveManager.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(SaveManager)
        self.gridLayout.setObjectName("gridLayout")
        self.tw_saves = TreeWidget(SaveManager)
        self.tw_saves.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_saves.setColumnCount(1)
        self.tw_saves.setObjectName("tw_saves")
        self.tw_saves.headerItem().setText(0, "1")
        self.tw_saves.header().setVisible(False)
        self.gridLayout.addWidget(self.tw_saves, 0, 0, 1, 1)

        self.retranslateUi(SaveManager)
        QtCore.QMetaObject.connectSlotsByName(SaveManager)

    def retranslateUi(self, SaveManager):
        _translate = QtCore.QCoreApplication.translate
        SaveManager.setWindowTitle(_translate("SaveManager", "存档管理"))
from qfluentwidgets import TreeWidget
