# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Functions\TaskManager\TaskItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TaskItem(object):
    def setupUi(self, TaskItem):
        TaskItem.setObjectName("TaskItem")
        TaskItem.resize(512, 78)
        TaskItem.setWindowTitle("")
        self.gridLayout = QtWidgets.QGridLayout(TaskItem)
        self.gridLayout.setObjectName("gridLayout")
        self.l_status = QtWidgets.QLabel(TaskItem)
        self.l_status.setText("")
        self.l_status.setObjectName("l_status")
        self.gridLayout.addWidget(self.l_status, 1, 0, 1, 1)
        self.pbr_progress = ProgressBar(TaskItem)
        self.pbr_progress.setMaximum(0)
        self.pbr_progress.setProperty("value", 0)
        self.pbr_progress.setObjectName("pbr_progress")
        self.gridLayout.addWidget(self.pbr_progress, 2, 0, 1, 1)
        self.l_name = QtWidgets.QLabel(TaskItem)
        self.l_name.setText("")
        self.l_name.setObjectName("l_name")
        self.gridLayout.addWidget(self.l_name, 0, 0, 1, 1)

        self.retranslateUi(TaskItem)
        QtCore.QMetaObject.connectSlotsByName(TaskItem)

    def retranslateUi(self, TaskItem):
        pass
from qfluentwidgets import ProgressBar
