# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Functions\WidgetManager\WidgetManger.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetManager(object):
    def setupUi(self, WidgetManager):
        WidgetManager.setObjectName("WidgetManager")
        WidgetManager.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(WidgetManager)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_stop = PushButton(WidgetManager)
        self.pb_stop.setObjectName("pb_stop")
        self.gridLayout.addWidget(self.pb_stop, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.tw_tasks = TreeWidget(WidgetManager)
        self.tw_tasks.setObjectName("tw_tasks")
        self.tw_tasks.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.tw_tasks, 0, 0, 1, 2)

        self.retranslateUi(WidgetManager)
        QtCore.QMetaObject.connectSlotsByName(WidgetManager)

    def retranslateUi(self, WidgetManager):
        _translate = QtCore.QCoreApplication.translate
        WidgetManager.setWindowTitle(_translate("WidgetManager", "控件管理器"))
        self.pb_stop.setText(_translate("WidgetManager", "停止"))
from qfluentwidgets import PushButton, TreeWidget
