# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Help\Links\Links.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Links(object):
    def setupUi(self, Links):
        Links.setObjectName("Links")
        Links.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(Links)
        self.gridLayout.setObjectName("gridLayout")
        self.ScrollArea = ScrollArea(Links)
        self.ScrollArea.setStyleSheet("QScrollArea{\n"
"    border:none;\n"
"}")
        self.ScrollArea.setWidgetResizable(True)
        self.ScrollArea.setObjectName("ScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 982, 600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pb_wiki = PushButton(self.groupBox)
        self.pb_wiki.setObjectName("pb_wiki")
        self.gridLayout_3.addWidget(self.pb_wiki, 1, 0, 1, 1)
        self.pb_mcofficialweb = PushButton(self.groupBox)
        self.pb_mcofficialweb.setObjectName("pb_mcofficialweb")
        self.gridLayout_3.addWidget(self.pb_mcofficialweb, 0, 0, 1, 1)
        self.pb_mcmod = PushButton(self.groupBox)
        self.pb_mcmod.setObjectName("pb_mcmod")
        self.gridLayout_3.addWidget(self.pb_mcmod, 2, 0, 1, 1)
        self.pb_plugin = PushButton(self.groupBox)
        self.pb_plugin.setObjectName("pb_plugin")
        self.gridLayout_3.addWidget(self.pb_plugin, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pb_openjdk = PushButton(self.groupBox_2)
        self.pb_openjdk.setObjectName("pb_openjdk")
        self.gridLayout_4.addWidget(self.pb_openjdk, 1, 0, 1, 1)
        self.pb_dragonwell = PushButton(self.groupBox_2)
        self.pb_dragonwell.setObjectName("pb_dragonwell")
        self.gridLayout_4.addWidget(self.pb_dragonwell, 3, 0, 1, 1)
        self.pb_javaofficialweb = PushButton(self.groupBox_2)
        self.pb_javaofficialweb.setObjectName("pb_javaofficialweb")
        self.gridLayout_4.addWidget(self.pb_javaofficialweb, 0, 0, 1, 1)
        self.pb_azul = PushButton(self.groupBox_2)
        self.pb_azul.setObjectName("pb_azul")
        self.gridLayout_4.addWidget(self.pb_azul, 2, 0, 1, 1)
        self.pb_graalvm = PushButton(self.groupBox_2)
        self.pb_graalvm.setObjectName("pb_graalvm")
        self.gridLayout_4.addWidget(self.pb_graalvm, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.ScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.ScrollArea, 0, 0, 1, 1)

        self.retranslateUi(Links)
        QtCore.QMetaObject.connectSlotsByName(Links)

    def retranslateUi(self, Links):
        _translate = QtCore.QCoreApplication.translate
        Links.setWindowTitle(_translate("Links", "常用网站"))
        self.groupBox.setTitle(_translate("Links", "Minecraft"))
        self.pb_wiki.setText(_translate("Links", "Minecraft Wiki"))
        self.pb_mcofficialweb.setText(_translate("Links", "官网"))
        self.pb_mcmod.setText(_translate("Links", "MC 百科"))
        self.pb_plugin.setText(_translate("Links", "插件百科"))
        self.groupBox_2.setTitle(_translate("Links", "Java"))
        self.pb_openjdk.setText(_translate("Links", "OpenJDK"))
        self.pb_dragonwell.setText(_translate("Links", "Dragonwell"))
        self.pb_javaofficialweb.setText(_translate("Links", "官网"))
        self.pb_azul.setText(_translate("Links", "Azul"))
        self.pb_graalvm.setText(_translate("Links", "GraalVM"))
from qfluentwidgets import PushButton, ScrollArea
