# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Functions\GameManager\ScreenshotManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScreenshotManager(object):
    def setupUi(self, ScreenshotManager):
        ScreenshotManager.setObjectName("ScreenshotManager")
        ScreenshotManager.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(ScreenshotManager)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.pb_openfolder = PushButton(ScreenshotManager)
        self.pb_openfolder.setObjectName("pb_openfolder")
        self.gridLayout.addWidget(self.pb_openfolder, 0, 0, 1, 1)
        self.w_operate = QtWidgets.QWidget(ScreenshotManager)
        self.w_operate.setEnabled(True)
        self.w_operate.setObjectName("w_operate")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.w_operate)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pb_rename = PushButton(self.w_operate)
        self.pb_rename.setEnabled(True)
        self.pb_rename.setObjectName("pb_rename")
        self.gridLayout_3.addWidget(self.pb_rename, 0, 1, 1, 1)
        self.pb_del = PushButton(self.w_operate)
        self.pb_del.setEnabled(True)
        self.pb_del.setObjectName("pb_del")
        self.gridLayout_3.addWidget(self.pb_del, 0, 2, 1, 1)
        self.pb_open = PushButton(self.w_operate)
        self.pb_open.setObjectName("pb_open")
        self.gridLayout_3.addWidget(self.pb_open, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.w_operate, 0, 2, 1, 1)
        self.lw_overview = ListWidget(ScreenshotManager)
        self.lw_overview.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lw_overview.setIconSize(QtCore.QSize(256, 256))
        self.lw_overview.setMovement(QtWidgets.QListView.Static)
        self.lw_overview.setFlow(QtWidgets.QListView.LeftToRight)
        self.lw_overview.setResizeMode(QtWidgets.QListView.Adjust)
        self.lw_overview.setViewMode(QtWidgets.QListView.IconMode)
        self.lw_overview.setWordWrap(True)
        self.lw_overview.setSelectionRectVisible(False)
        self.lw_overview.setObjectName("lw_overview")
        self.gridLayout.addWidget(self.lw_overview, 1, 0, 1, 4)

        self.retranslateUi(ScreenshotManager)
        QtCore.QMetaObject.connectSlotsByName(ScreenshotManager)

    def retranslateUi(self, ScreenshotManager):
        _translate = QtCore.QCoreApplication.translate
        ScreenshotManager.setWindowTitle(_translate("ScreenshotManager", "截图管理"))
        self.pb_openfolder.setText(_translate("ScreenshotManager", "打开截图文件夹"))
        self.pb_rename.setText(_translate("ScreenshotManager", "重命名"))
        self.pb_del.setText(_translate("ScreenshotManager", "删除"))
        self.pb_open.setText(_translate("ScreenshotManager", "打开"))
from qfluentwidgets import ListWidget, PushButton
