# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Ui\Homepage\AllFunctions.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AllFunctions(object):
    def setupUi(self, AllFunctions):
        AllFunctions.setObjectName("AllFunctions")
        AllFunctions.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(AllFunctions)
        self.gridLayout.setObjectName("gridLayout")
        self.tw_func = QtWidgets.QTableWidget(AllFunctions)
        self.tw_func.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_func.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tw_func.setObjectName("tw_func")
        self.tw_func.setColumnCount(0)
        self.tw_func.setRowCount(0)
        self.tw_func.horizontalHeader().setVisible(False)
        self.tw_func.horizontalHeader().setDefaultSectionSize(45)
        self.tw_func.horizontalHeader().setHighlightSections(False)
        self.tw_func.horizontalHeader().setMinimumSectionSize(45)
        self.tw_func.verticalHeader().setVisible(False)
        self.tw_func.verticalHeader().setDefaultSectionSize(45)
        self.tw_func.verticalHeader().setHighlightSections(False)
        self.tw_func.verticalHeader().setMinimumSectionSize(45)
        self.gridLayout.addWidget(self.tw_func, 0, 0, 1, 1)

        self.retranslateUi(AllFunctions)
        QtCore.QMetaObject.connectSlotsByName(AllFunctions)

    def retranslateUi(self, AllFunctions):
        _translate = QtCore.QCoreApplication.translate
        AllFunctions.setWindowTitle(_translate("AllFunctions", "所有应用"))
