# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Ui\Homepage\Homepage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Homepage(object):
    def setupUi(self, Homepage):
        Homepage.setObjectName("Homepage")
        Homepage.resize(1000, 618)
        self.f_panel = QtWidgets.QFrame(Homepage)
        self.f_panel.setGeometry(QtCore.QRect(0, 0, 45, 618))
        self.f_panel.setStyleSheet("QFrame{\n"
"    background-color:rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    border:none;\n"
"    text-align:left;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(229,229,229);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    border-left:2px solid rgb(0,0,0);\n"
"}")
        self.f_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_panel.setObjectName("f_panel")
        self.pb_launch = QCustomButton(self.f_panel)
        self.pb_launch.setGeometry(QtCore.QRect(0, 45, 45, 45))
        self.pb_launch.setText("")
        self.pb_launch.setIconSize(QtCore.QSize(20, 20))
        self.pb_launch.setCheckable(True)
        self.pb_launch.setAutoExclusive(True)
        self.pb_launch.setObjectName("pb_launch")
        self.pb_download = QCustomButton(self.f_panel)
        self.pb_download.setGeometry(QtCore.QRect(0, 90, 45, 45))
        self.pb_download.setText("")
        self.pb_download.setIconSize(QtCore.QSize(20, 20))
        self.pb_download.setCheckable(True)
        self.pb_download.setAutoExclusive(True)
        self.pb_download.setObjectName("pb_download")
        self.pb_detail = QtWidgets.QPushButton(self.f_panel)
        self.pb_detail.setGeometry(QtCore.QRect(0, 0, 45, 45))
        self.pb_detail.setText("")
        self.pb_detail.setObjectName("pb_detail")
        self.pb_user = QCustomButton(self.f_panel)
        self.pb_user.setGeometry(QtCore.QRect(0, 528, 45, 45))
        self.pb_user.setText("")
        self.pb_user.setCheckable(True)
        self.pb_user.setAutoExclusive(True)
        self.pb_user.setObjectName("pb_user")
        self.pb_setting = QCustomButton(self.f_panel)
        self.pb_setting.setGeometry(QtCore.QRect(0, 573, 45, 45))
        self.pb_setting.setText("")
        self.pb_setting.setCheckable(True)
        self.pb_setting.setAutoExclusive(True)
        self.pb_setting.setObjectName("pb_setting")
        self.w_ui = QtWidgets.QWidget(Homepage)
        self.w_ui.setGeometry(QtCore.QRect(45, 0, 955, 618))
        self.w_ui.setObjectName("w_ui")

        self.retranslateUi(Homepage)
        QtCore.QMetaObject.connectSlotsByName(Homepage)

    def retranslateUi(self, Homepage):
        _translate = QtCore.QCoreApplication.translate
        Homepage.setWindowTitle(_translate("Homepage", "主页"))
from Ui.QCustomButton import QCustomButton
