# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Ui\Homepage\Homepage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Homepage(object):
    def setupUi(self, Homepage):
        Homepage.setObjectName("Homepage")
        Homepage.resize(1000, 618)
        self.f_panel = QtWidgets.QFrame(Homepage)
        self.f_panel.setGeometry(QtCore.QRect(0, 0, 45, 618))
        self.f_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_panel.setObjectName("f_panel")
        self.pb_detail = QtWidgets.QPushButton(self.f_panel)
        self.pb_detail.setGeometry(QtCore.QRect(0, 0, 45, 45))
        self.pb_detail.setText("")
        self.pb_detail.setObjectName("pb_detail")
        self.pb_user = QCustomButton(self.f_panel)
        self.pb_user.setGeometry(QtCore.QRect(0, 483, 45, 45))
        self.pb_user.setText("")
        self.pb_user.setCheckable(False)
        self.pb_user.setAutoExclusive(False)
        self.pb_user.setObjectName("pb_user")
        self.pb_setting = QCustomButton(self.f_panel)
        self.pb_setting.setGeometry(QtCore.QRect(0, 528, 45, 45))
        self.pb_setting.setText("")
        self.pb_setting.setCheckable(False)
        self.pb_setting.setAutoExclusive(False)
        self.pb_setting.setObjectName("pb_setting")
        self.pb_allfunc = QCustomButton(self.f_panel)
        self.pb_allfunc.setGeometry(QtCore.QRect(0, 90, 45, 45))
        self.pb_allfunc.setText("")
        self.pb_allfunc.setCheckable(True)
        self.pb_allfunc.setAutoExclusive(True)
        self.pb_allfunc.setObjectName("pb_allfunc")
        self.pb_software = QtWidgets.QPushButton(self.f_panel)
        self.pb_software.setGeometry(QtCore.QRect(0, 573, 45, 45))
        self.pb_software.setText("")
        self.pb_software.setObjectName("pb_software")
        self.w_ui = QtWidgets.QWidget(Homepage)
        self.w_ui.setGeometry(QtCore.QRect(45, 0, 955, 618))
        self.w_ui.setObjectName("w_ui")

        self.retranslateUi(Homepage)
        QtCore.QMetaObject.connectSlotsByName(Homepage)

    def retranslateUi(self, Homepage):
        _translate = QtCore.QCoreApplication.translate
        Homepage.setWindowTitle(_translate("Homepage", "主页"))
from Ui.QCustomButton import QCustomButton
