# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\System\Setting\SettingWidgets\ListSettingWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListSettingWidget(object):
    def setupUi(self, ListSettingWidget):
        ListSettingWidget.setObjectName("ListSettingWidget")
        ListSettingWidget.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(ListSettingWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_add = QtWidgets.QPushButton(ListSettingWidget)
        self.pb_add.setObjectName("pb_add")
        self.gridLayout.addWidget(self.pb_add, 1, 1, 1, 1)
        self.pb_promote = QtWidgets.QPushButton(ListSettingWidget)
        self.pb_promote.setObjectName("pb_promote")
        self.gridLayout.addWidget(self.pb_promote, 1, 3, 1, 1)
        self.pb_delete = QtWidgets.QPushButton(ListSettingWidget)
        self.pb_delete.setObjectName("pb_delete")
        self.gridLayout.addWidget(self.pb_delete, 1, 2, 1, 1)
        self.pb_promote_top = QtWidgets.QPushButton(ListSettingWidget)
        self.pb_promote_top.setObjectName("pb_promote_top")
        self.gridLayout.addWidget(self.pb_promote_top, 1, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.lw_values = QtWidgets.QListWidget(ListSettingWidget)
        self.lw_values.setObjectName("lw_values")
        self.gridLayout.addWidget(self.lw_values, 0, 0, 1, 5)

        self.retranslateUi(ListSettingWidget)
        QtCore.QMetaObject.connectSlotsByName(ListSettingWidget)

    def retranslateUi(self, ListSettingWidget):
        _translate = QtCore.QCoreApplication.translate
        ListSettingWidget.setWindowTitle(_translate("ListSettingWidget", "设置"))
        self.pb_add.setText(_translate("ListSettingWidget", "添加"))
        self.pb_promote.setText(_translate("ListSettingWidget", "提升"))
        self.pb_delete.setText(_translate("ListSettingWidget", "删除"))
        self.pb_promote_top.setText(_translate("ListSettingWidget", "提至最高"))
