# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Ui\Launcher\ChooseVersion.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChooseVersion(object):
    def setupUi(self, ChooseVersion):
        ChooseVersion.setObjectName("ChooseVersion")
        ChooseVersion.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(ChooseVersion)
        self.gridLayout.setObjectName("gridLayout")
        self.lw_versions = QtWidgets.QListWidget(ChooseVersion)
        self.lw_versions.setObjectName("lw_versions")
        self.gridLayout.addWidget(self.lw_versions, 0, 0, 1, 1)

        self.retranslateUi(ChooseVersion)
        QtCore.QMetaObject.connectSlotsByName(ChooseVersion)

    def retranslateUi(self, ChooseVersion):
        _translate = QtCore.QCoreApplication.translate
        ChooseVersion.setWindowTitle(_translate("ChooseVersion", "选择版本"))
