# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\User\PCG\FMCL\FMCL\Functions\GameLauncher\StartupDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartupDialog(object):
    def setupUi(self, StartupDialog):
        StartupDialog.setObjectName("StartupDialog")
        StartupDialog.resize(500, 309)
        self.gridLayout = QtWidgets.QGridLayout(StartupDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_cancel = PushButton(StartupDialog)
        self.pb_cancel.setObjectName("pb_cancel")
        self.gridLayout.addWidget(self.pb_cancel, 4, 1, 1, 1)
        self.pb_ok = PushButton(StartupDialog)
        self.pb_ok.setObjectName("pb_ok")
        self.gridLayout.addWidget(self.pb_ok, 4, 0, 1, 1)
        self.cb_toberun = ComboBox(StartupDialog)
        self.cb_toberun.setObjectName("cb_toberun")
        self.gridLayout.addWidget(self.cb_toberun, 1, 0, 1, 2)
        self.cb_running = ComboBox(StartupDialog)
        self.cb_running.setObjectName("cb_running")
        self.gridLayout.addWidget(self.cb_running, 3, 0, 1, 2)
        self.ckb_running = CheckBox(StartupDialog)
        self.ckb_running.setAutoExclusive(True)
        self.ckb_running.setObjectName("ckb_running")
        self.gridLayout.addWidget(self.ckb_running, 2, 0, 1, 2)
        self.ckb_toberun = CheckBox(StartupDialog)
        self.ckb_toberun.setChecked(True)
        self.ckb_toberun.setAutoExclusive(True)
        self.ckb_toberun.setObjectName("ckb_toberun")
        self.gridLayout.addWidget(self.ckb_toberun, 0, 0, 1, 2)

        self.retranslateUi(StartupDialog)
        QtCore.QMetaObject.connectSlotsByName(StartupDialog)

    def retranslateUi(self, StartupDialog):
        _translate = QtCore.QCoreApplication.translate
        StartupDialog.setWindowTitle(_translate("StartupDialog", "准备运行游戏"))
        self.pb_cancel.setText(_translate("StartupDialog", "取消"))
        self.pb_ok.setText(_translate("StartupDialog", "确定"))
        self.ckb_running.setText(_translate("StartupDialog", "或正在运行的游戏"))
        self.ckb_toberun.setText(_translate("StartupDialog", "选择要运行的游戏"))
from qfluentwidgets import CheckBox, ComboBox, PushButton
