# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Functions\GameManager\SaveManager\SaveItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveItem(object):
    def setupUi(self, SaveItem):
        SaveItem.setObjectName("SaveItem")
        SaveItem.resize(512, 128)
        self.gridLayout = QtWidgets.QGridLayout(SaveItem)
        self.gridLayout.setObjectName("gridLayout")
        self.l_icon = QtWidgets.QLabel(SaveItem)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_icon.sizePolicy().hasHeightForWidth())
        self.l_icon.setSizePolicy(sizePolicy)
        self.l_icon.setMinimumSize(QtCore.QSize(100, 100))
        self.l_icon.setMaximumSize(QtCore.QSize(100, 100))
        self.l_icon.setText("")
        self.l_icon.setObjectName("l_icon")
        self.gridLayout.addWidget(self.l_icon, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.l_levelname = QtWidgets.QLabel(SaveItem)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.l_levelname.setFont(font)
        self.l_levelname.setText("")
        self.l_levelname.setObjectName("l_levelname")
        self.gridLayout_2.addWidget(self.l_levelname, 0, 0, 1, 1)
        self.l_info2 = QtWidgets.QLabel(SaveItem)
        self.l_info2.setText("")
        self.l_info2.setObjectName("l_info2")
        self.gridLayout_2.addWidget(self.l_info2, 3, 0, 1, 1)
        self.l_info1 = QtWidgets.QLabel(SaveItem)
        self.l_info1.setMinimumSize(QtCore.QSize(0, 0))
        self.l_info1.setText("")
        self.l_info1.setWordWrap(False)
        self.l_info1.setObjectName("l_info1")
        self.gridLayout_2.addWidget(self.l_info1, 1, 0, 1, 1)
        self.pb_del = PushButton(SaveItem)
        self.pb_del.setObjectName("pb_del")
        self.gridLayout_2.addWidget(self.pb_del, 0, 1, 1, 1)
        self.pb_openfolder = PushButton(SaveItem)
        self.pb_openfolder.setObjectName("pb_openfolder")
        self.gridLayout_2.addWidget(self.pb_openfolder, 1, 1, 1, 1)
        self.pb_viewnbt = PushButton(SaveItem)
        self.pb_viewnbt.setObjectName("pb_viewnbt")
        self.gridLayout_2.addWidget(self.pb_viewnbt, 3, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 1, 1, 1)

        self.retranslateUi(SaveItem)
        QtCore.QMetaObject.connectSlotsByName(SaveItem)

    def retranslateUi(self, SaveItem):
        _translate = QtCore.QCoreApplication.translate
        SaveItem.setWindowTitle(_translate("SaveItem", "SaveItem"))
        self.pb_del.setText(_translate("SaveItem", "删除"))
        self.pb_openfolder.setText(_translate("SaveItem", "打开文件夹"))
        self.pb_viewnbt.setText(_translate("SaveItem", "查看NBT"))
from qfluentwidgets import PushButton
