# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\QtFBN\Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 314)
        Dialog.setWindowTitle("")
        self.l_title = QtWidgets.QLabel(Dialog)
        self.l_title.setGeometry(QtCore.QRect(0, 0, 500, 32))
        self.l_title.setText("")
        self.l_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.l_title.setObjectName("l_title")
        self.l_msg = QtWidgets.QLabel(Dialog)
        self.l_msg.setGeometry(QtCore.QRect(0, 32, 500, 250))
        self.l_msg.setText("")
        self.l_msg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.l_msg.setObjectName("l_msg")
        self.pb_ok = QtWidgets.QPushButton(Dialog)
        self.pb_ok.setGeometry(QtCore.QRect(372, 282, 64, 32))
        self.pb_ok.setObjectName("pb_ok")
        self.pb_cancel = QtWidgets.QPushButton(Dialog)
        self.pb_cancel.setGeometry(QtCore.QRect(436, 282, 64, 32))
        self.pb_cancel.setObjectName("pb_cancel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.pb_ok.setText(_translate("Dialog", "确定"))
        self.pb_cancel.setText(_translate("Dialog", "取消"))
