# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Functions\ModManager\ModItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModItem(object):
    def setupUi(self, ModItem):
        ModItem.setObjectName("ModItem")
        ModItem.resize(256, 64)
        self.gl_main = QtWidgets.QGridLayout(ModItem)
        self.gl_main.setContentsMargins(-1, 0, -1, 0)
        self.gl_main.setObjectName("gl_main")
        self.l_modname = QtWidgets.QLabel(ModItem)
        self.l_modname.setText("")
        self.l_modname.setWordWrap(False)
        self.l_modname.setObjectName("l_modname")
        self.gl_main.addWidget(self.l_modname, 0, 1, 1, 1)
        self.cb_modenabled = QtWidgets.QCheckBox(ModItem)
        self.cb_modenabled.setText("")
        self.cb_modenabled.setTristate(False)
        self.cb_modenabled.setObjectName("cb_modenabled")
        self.gl_main.addWidget(self.cb_modenabled, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gl_main.addItem(spacerItem, 0, 2, 1, 1)

        self.retranslateUi(ModItem)
        QtCore.QMetaObject.connectSlotsByName(ModItem)

    def retranslateUi(self, ModItem):
        _translate = QtCore.QCoreApplication.translate
        ModItem.setWindowTitle(_translate("ModItem", "Mod"))
