# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Ui\News\NewsDetail.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewsDetail(object):
    def setupUi(self, NewsDetail):
        NewsDetail.setObjectName("NewsDetail")
        NewsDetail.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(NewsDetail)
        self.gridLayout.setObjectName("gridLayout")
        self.l_title = QtWidgets.QLabel(NewsDetail)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l_title.setFont(font)
        self.l_title.setText("")
        self.l_title.setWordWrap(True)
        self.l_title.setObjectName("l_title")
        self.gridLayout.addWidget(self.l_title, 0, 0, 1, 1)
        self.pb_openurl = QtWidgets.QPushButton(NewsDetail)
        self.pb_openurl.setObjectName("pb_openurl")
        self.gridLayout.addWidget(self.pb_openurl, 0, 1, 1, 1)
        self.te_body = QtWidgets.QTextEdit(NewsDetail)
        self.te_body.setReadOnly(True)
        self.te_body.setObjectName("te_body")
        self.gridLayout.addWidget(self.te_body, 1, 0, 1, 2)

        self.retranslateUi(NewsDetail)
        QtCore.QMetaObject.connectSlotsByName(NewsDetail)

    def retranslateUi(self, NewsDetail):
        _translate = QtCore.QCoreApplication.translate
        NewsDetail.setWindowTitle(_translate("NewsDetail", "新闻详情"))
        self.pb_openurl.setText(_translate("NewsDetail", "打开网址"))
