translate = {
    "桌面": "Desktop",
    "启动": "Launch",
    "管理": "Manage",
    "下载": "Download",
    "前置Mod": "Pre Mod",
    "保存": "Save",
    "下载量": "downloads",
    "热度": "hot",
    "创建日期": "create",
    "更新日期": "updata",
    "任务结束": "Task finished",
    "错误": "Error",
    "取消": "Cancel",
    "所有应用": "All functions",
    "下载Minecraft": "Download Minecraft",
    "下载Mod": "Downlaod Mod",
    "更多": "More",
    "设置": "Setting",
    "未选择用户": "No user selected",
    "更改": "Change",
    "添加": "Add",
    "输入要添加的内容": "Enter what to add",
    "选择文件夹": "Select Folder",
    "删除": "Delete",
    "确认删除": "Confirm deletion",
    "游戏路径": "Game path",
    "游戏窗口宽度": "Game window width",
    "游戏窗口高度": "Game window height",
    "最大内存": "Max memory",
    "最小内存": "Min memory",
    "Java路径": "Java path",
    "背景图片": "Background image",
    "主题": "Theme",
    "选择图标": "Choose icon",
    "启用": "Enable",
    "禁用": "Disable",
    "该版本不可用Mod": "This version is not available Mod",
    "安装新版本": "Install new version",
    "有新版本": "Have new version",
    "确定更新吗": "Confierm updata",
    "显示桌面": "Show desktop",
    "下载管理": "Download manage",
    "主页": "Homepage",
    "新用户": "New user",
    "用户": "User",
    "版本管理": "Version manage",
    "图标选择": "Icon selector",
    "自定义图标": "Custom icon",
    "这是自定义图标的路径": "This is the path of the custom icon",
    "确定": "Ok",
    "基础": "Basic",
    "Fabric版本": "Fabric version",
    "Optifine版本": "Optifine version",
    "打开版本文件夹": "Open version folder",
    "版本": "Version",
    "重新安装": "Reinstall",
    "名称": "Name",
    "Forge版本": "Forge version",
    "更改图标": "Change icon",
    "Mod管理": "Mod manage",
    "打开mod文件夹": "Open mod folder",
    "请输入用户名": "please enter one user name",
    "离线登录": "Offline",
    "所有语言": "All languages",
    "关于": "About",
    "打开开源网址": "Open the open source website",
    "鸣谢": "Acknowledge",
    "打开网址": "Open website",
    "bangbang93: 提供镜像源": "bangbang93: provide image source",
    "huanghongxun: 提供技术帮助(HMCL)": "huanghongxun: provide technical assistance (HMCL)"
}
