# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Functions\ResourceDownloader\ResDetail.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResDetail(object):
    def setupUi(self, ResDetail):
        ResDetail.setObjectName("ResDetail")
        ResDetail.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(ResDetail)
        self.gridLayout.setObjectName("gridLayout")
        self.ScrollArea = ScrollArea(ResDetail)
        self.ScrollArea.setStyleSheet("QScrollArea{\n"
"    border:none;\n"
"}")
        self.ScrollArea.setWidgetResizable(True)
        self.ScrollArea.setObjectName("ScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 982, 600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.hl_operates = QtWidgets.QHBoxLayout()
        self.hl_operates.setObjectName("hl_operates")
        self.gridLayout_2.addLayout(self.hl_operates, 1, 0, 1, 1)
        self.vl_resinfo = QtWidgets.QVBoxLayout()
        self.vl_resinfo.setSpacing(0)
        self.vl_resinfo.setObjectName("vl_resinfo")
        self.gridLayout_2.addLayout(self.vl_resinfo, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.tw_versions = TreeWidget(self.scrollAreaWidgetContents)
        self.tw_versions.setObjectName("tw_versions")
        self.tw_versions.headerItem().setText(0, "1")
        self.tw_versions.header().setVisible(False)
        self.gridLayout_3.addWidget(self.tw_versions, 1, 0, 1, 1)
        self.ScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.ScrollArea, 0, 0, 1, 1)

        self.retranslateUi(ResDetail)
        QtCore.QMetaObject.connectSlotsByName(ResDetail)

    def retranslateUi(self, ResDetail):
        _translate = QtCore.QCoreApplication.translate
        ResDetail.setWindowTitle(_translate("ResDetail", "模组详情"))
from qfluentwidgets import ScrollArea, TreeWidget
