# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Functions\ResourceDownloader\VersionItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VersionItem(object):
    def setupUi(self, VersionItem):
        VersionItem.setObjectName("VersionItem")
        VersionItem.resize(400, 88)
        VersionItem.setWindowTitle("")
        self.gridLayout = QtWidgets.QGridLayout(VersionItem)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.l_info = QtWidgets.QLabel(VersionItem)
        self.l_info.setText("")
        self.l_info.setWordWrap(False)
        self.l_info.setObjectName("l_info")
        self.gridLayout.addWidget(self.l_info, 1, 0, 1, 1)
        self.pb_download = PushButton(VersionItem)
        self.pb_download.setObjectName("pb_download")
        self.gridLayout.addWidget(self.pb_download, 0, 3, 1, 1)
        self.pb_install = PushButton(VersionItem)
        self.pb_install.setObjectName("pb_install")
        self.gridLayout.addWidget(self.pb_install, 1, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.l_name = QtWidgets.QLabel(VersionItem)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.l_name.setFont(font)
        self.l_name.setText("")
        self.l_name.setWordWrap(False)
        self.l_name.setObjectName("l_name")
        self.gridLayout.addWidget(self.l_name, 0, 0, 1, 1)
        self.hl_label = QtWidgets.QHBoxLayout()
        self.hl_label.setObjectName("hl_label")
        self.gridLayout.addLayout(self.hl_label, 0, 1, 1, 1)

        self.retranslateUi(VersionItem)
        QtCore.QMetaObject.connectSlotsByName(VersionItem)

    def retranslateUi(self, VersionItem):
        _translate = QtCore.QCoreApplication.translate
        self.pb_download.setText(_translate("VersionItem", "下载"))
        self.pb_install.setText(_translate("VersionItem", "安装"))
from qfluentwidgets import PushButton
