# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Functions\SettingEditor\SettingEditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingEditor(object):
    def setupUi(self, SettingEditor):
        SettingEditor.setObjectName("SettingEditor")
        SettingEditor.resize(1000, 618)
        self.gridLayout_2 = QtWidgets.QGridLayout(SettingEditor)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(SettingEditor)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tw_setting = TreeWidget(self.splitter)
        self.tw_setting.setObjectName("tw_setting")
        self.tw_setting.headerItem().setText(0, "1")
        self.tw_setting.header().setVisible(False)
        self.sa_setting = ScrollArea(self.splitter)
        self.sa_setting.setWidgetResizable(True)
        self.sa_setting.setObjectName("sa_setting")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 124, 598))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.w_setting = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.w_setting.setObjectName("w_setting")
        self.gl_setting = QtWidgets.QGridLayout(self.w_setting)
        self.gl_setting.setObjectName("gl_setting")
        self.gridLayout.addWidget(self.w_setting, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.sa_setting.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 2)

        self.retranslateUi(SettingEditor)
        QtCore.QMetaObject.connectSlotsByName(SettingEditor)

    def retranslateUi(self, SettingEditor):
        _translate = QtCore.QCoreApplication.translate
        SettingEditor.setWindowTitle(_translate("SettingEditor", "设置"))
from qfluentwidgets import ScrollArea, TreeWidget
