# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Functions\ModDownloader\ModFound.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModFound(object):
    def setupUi(self, ModFound):
        ModFound.setObjectName("ModFound")
        ModFound.resize(256, 82)
        self.gridLayout = QtWidgets.QGridLayout(ModFound)
        self.gridLayout.setObjectName("gridLayout")
        self.l_title = QtWidgets.QLabel(ModFound)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.l_title.setFont(font)
        self.l_title.setText("")
        self.l_title.setWordWrap(True)
        self.l_title.setObjectName("l_title")
        self.gridLayout.addWidget(self.l_title, 0, 1, 1, 1)
        self.l_description = QtWidgets.QLabel(ModFound)
        self.l_description.setText("")
        self.l_description.setWordWrap(True)
        self.l_description.setObjectName("l_description")
        self.gridLayout.addWidget(self.l_description, 1, 1, 1, 1)
        self.l_icon = QtWidgets.QLabel(ModFound)
        self.l_icon.setMinimumSize(QtCore.QSize(64, 64))
        self.l_icon.setMaximumSize(QtCore.QSize(64, 64))
        self.l_icon.setText("")
        self.l_icon.setObjectName("l_icon")
        self.gridLayout.addWidget(self.l_icon, 0, 0, 2, 1)

        self.retranslateUi(ModFound)
        QtCore.QMetaObject.connectSlotsByName(ModFound)

    def retranslateUi(self, ModFound):
        _translate = QtCore.QCoreApplication.translate
        ModFound.setWindowTitle(_translate("ModFound", "ModFound"))
