# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModDownloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModDownloader(object):
    def setupUi(self, ModDownloader):
        ModDownloader.setObjectName("ModDownloader")
        ModDownloader.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(ModDownloader)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = ScrollArea(ModDownloader)
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"    border:none;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 982, 600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tw_mods = TreeWidget(self.scrollAreaWidgetContents)
        self.tw_mods.setObjectName("tw_mods")
        self.tw_mods.headerItem().setText(0, "1")
        self.tw_mods.header().setVisible(False)
        self.gridLayout_2.addWidget(self.tw_mods, 2, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 3, 1, 1)
        self.cb_downloadsource = ComboBox(self.scrollAreaWidgetContents)
        self.cb_downloadsource.setObjectName("cb_downloadsource")
        self.gridLayout_3.addWidget(self.cb_downloadsource, 0, 4, 1, 1)
        self.le_name = LineEdit(self.scrollAreaWidgetContents)
        self.le_name.setObjectName("le_name")
        self.gridLayout_3.addWidget(self.le_name, 0, 1, 1, 2)
        self.cb_sort = ComboBox(self.scrollAreaWidgetContents)
        self.cb_sort.setObjectName("cb_sort")
        self.gridLayout_3.addWidget(self.cb_sort, 1, 1, 1, 2)
        self.pb_search = PushButton(self.scrollAreaWidgetContents)
        self.pb_search.setObjectName("pb_search")
        self.gridLayout_3.addWidget(self.pb_search, 1, 3, 1, 1)
        self.pb_download = PushButton(self.scrollAreaWidgetContents)
        self.pb_download.setObjectName("pb_download")
        self.gridLayout_3.addWidget(self.pb_download, 1, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 3)
        self.tw_files = TreeWidget(self.scrollAreaWidgetContents)
        self.tw_files.setObjectName("tw_files")
        self.tw_files.headerItem().setText(0, "1")
        self.tw_files.header().setVisible(False)
        self.gridLayout_2.addWidget(self.tw_files, 2, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(ModDownloader)
        QtCore.QMetaObject.connectSlotsByName(ModDownloader)

    def retranslateUi(self, ModDownloader):
        _translate = QtCore.QCoreApplication.translate
        ModDownloader.setWindowTitle(_translate("ModDownloader", "Mod下载器"))
        self.label_3.setText(_translate("ModDownloader", "排序"))
        self.label.setText(_translate("ModDownloader", "名称"))
        self.label_2.setText(_translate("ModDownloader", "下载源"))
        self.pb_search.setText(_translate("ModDownloader", "搜索"))
        self.pb_download.setText(_translate("ModDownloader", "下载"))
from qfluentwidgets import ComboBox, LineEdit, PushButton, ScrollArea, TreeWidget
