# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Functions\ModDownloader\ModDetail.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModDetail(object):
    def setupUi(self, ModDetail):
        ModDetail.setObjectName("ModDetail")
        ModDetail.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(ModDetail)
        self.gridLayout.setObjectName("gridLayout")
        self.ScrollArea = ScrollArea(ModDetail)
        self.ScrollArea.setStyleSheet("QScrollArea{\n"
"    border:none;\n"
"}")
        self.ScrollArea.setWidgetResizable(True)
        self.ScrollArea.setObjectName("ScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 982, 600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tw_versions = TreeWidget(self.scrollAreaWidgetContents)
        self.tw_versions.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_versions.setWordWrap(True)
        self.tw_versions.setColumnCount(5)
        self.tw_versions.setObjectName("tw_versions")
        self.tw_versions.header().setVisible(True)
        self.gridLayout_3.addWidget(self.tw_versions, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.vl_modinfo = QtWidgets.QVBoxLayout()
        self.vl_modinfo.setSpacing(0)
        self.vl_modinfo.setObjectName("vl_modinfo")
        self.gridLayout_2.addLayout(self.vl_modinfo, 0, 0, 1, 1)
        self.hl_urls = QtWidgets.QHBoxLayout()
        self.hl_urls.setObjectName("hl_urls")
        self.gridLayout_2.addLayout(self.hl_urls, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.ScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.ScrollArea, 0, 0, 1, 1)

        self.retranslateUi(ModDetail)
        QtCore.QMetaObject.connectSlotsByName(ModDetail)

    def retranslateUi(self, ModDetail):
        _translate = QtCore.QCoreApplication.translate
        ModDetail.setWindowTitle(_translate("ModDetail", "模组详情"))
        self.tw_versions.headerItem().setText(0, _translate("ModDetail", "版本或名称"))
        self.tw_versions.headerItem().setText(1, _translate("ModDetail", "加载器或需求"))
        self.tw_versions.headerItem().setText(2, _translate("ModDetail", "类型"))
        self.tw_versions.headerItem().setText(3, _translate("ModDetail", "下载量"))
        self.tw_versions.headerItem().setText(4, _translate("ModDetail", "更新时间"))
from qfluentwidgets import ScrollArea, TreeWidget
