# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LittleSkin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LittleSkin(object):
    def setupUi(self, LittleSkin):
        LittleSkin.setObjectName("LittleSkin")
        LittleSkin.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(LittleSkin)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 1, 1, 1)
        self.le_password = LineEdit(LittleSkin)
        self.le_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_password.setObjectName("le_password")
        self.gridLayout.addWidget(self.le_password, 2, 1, 1, 1)
        self.pb_logon = PushButton(LittleSkin)
        self.pb_logon.setObjectName("pb_logon")
        self.gridLayout.addWidget(self.pb_logon, 3, 1, 1, 1)
        self.le_username = LineEdit(LittleSkin)
        self.le_username.setInputMask("")
        self.le_username.setObjectName("le_username")
        self.gridLayout.addWidget(self.le_username, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 2, 1, 1)

        self.retranslateUi(LittleSkin)
        QtCore.QMetaObject.connectSlotsByName(LittleSkin)

    def retranslateUi(self, LittleSkin):
        _translate = QtCore.QCoreApplication.translate
        LittleSkin.setWindowTitle(_translate("LittleSkin", "LittleSkin"))
        self.le_password.setPlaceholderText(_translate("LittleSkin", "密码"))
        self.pb_logon.setText(_translate("LittleSkin", "登录"))
        self.le_username.setPlaceholderText(_translate("LittleSkin", "邮箱"))
from qfluentwidgets import LineEdit, PushButton
