# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Functions\CreateUser\Offline.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Offline(object):
    def setupUi(self, Offline):
        Offline.setObjectName("Offline")
        Offline.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(Offline)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 1, 1, 1)
        self.pb_create = PushButton(Offline)
        self.pb_create.setObjectName("pb_create")
        self.gridLayout.addWidget(self.pb_create, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)
        self.le_username = LineEdit(Offline)
        self.le_username.setObjectName("le_username")
        self.gridLayout.addWidget(self.le_username, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 2, 1, 1)
        self.le_uuid = LineEdit(Offline)
        self.le_uuid.setInputMask("")
        self.le_uuid.setObjectName("le_uuid")
        self.gridLayout.addWidget(self.le_uuid, 2, 1, 1, 1)

        self.retranslateUi(Offline)
        QtCore.QMetaObject.connectSlotsByName(Offline)

    def retranslateUi(self, Offline):
        _translate = QtCore.QCoreApplication.translate
        Offline.setWindowTitle(_translate("Offline", "离线登录"))
        self.pb_create.setText(_translate("Offline", "创建"))
        self.le_username.setPlaceholderText(_translate("Offline", "输入用户名"))
        self.le_uuid.setPlaceholderText(_translate("Offline", "UUID, 留空将自动生成"))
from qfluentwidgets import LineEdit, PushButton
