# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\FMCL\Functions\CreateUser\Yggdrasil.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Yggdrasil(object):
    def setupUi(self, Yggdrasil):
        Yggdrasil.setObjectName("Yggdrasil")
        Yggdrasil.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(Yggdrasil)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.hl_links = QtWidgets.QHBoxLayout()
        self.hl_links.setObjectName("hl_links")
        self.pb_delete = TransparentToolButton(Yggdrasil)
        self.pb_delete.setObjectName("pb_delete")
        self.hl_links.addWidget(self.pb_delete)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_links.addItem(spacerItem1)
        self.gridLayout.addLayout(self.hl_links, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 3, 1, 1)
        self.le_username = LineEdit(Yggdrasil)
        self.le_username.setObjectName("le_username")
        self.gridLayout.addWidget(self.le_username, 2, 2, 1, 1)
        self.le_password = PasswordLineEdit(Yggdrasil)
        self.le_password.setObjectName("le_password")
        self.gridLayout.addWidget(self.le_password, 3, 2, 1, 1)
        self.l_username = QtWidgets.QLabel(Yggdrasil)
        self.l_username.setObjectName("l_username")
        self.gridLayout.addWidget(self.l_username, 2, 1, 1, 1)
        self.l_password = QtWidgets.QLabel(Yggdrasil)
        self.l_password.setObjectName("l_password")
        self.gridLayout.addWidget(self.l_password, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 5, 2, 1, 1)
        self.pb_login = PushButton(Yggdrasil)
        self.pb_login.setObjectName("pb_login")
        self.gridLayout.addWidget(self.pb_login, 4, 2, 1, 1)

        self.retranslateUi(Yggdrasil)
        QtCore.QMetaObject.connectSlotsByName(Yggdrasil)

    def retranslateUi(self, Yggdrasil):
        _translate = QtCore.QCoreApplication.translate
        Yggdrasil.setWindowTitle(_translate("Yggdrasil", "Yggdrasil"))
        self.l_username.setText(_translate("Yggdrasil", "用户名"))
        self.l_password.setText(_translate("Yggdrasil", "密码"))
        self.pb_login.setText(_translate("Yggdrasil", "登录"))
from qfluentwidgets import LineEdit, PasswordLineEdit, PushButton, TransparentToolButton
