# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\User\PCG\FMCL\FMCL\Functions\UserManager\UserInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserInfo(object):
    def setupUi(self, UserInfo):
        UserInfo.setObjectName("UserInfo")
        UserInfo.resize(512, 64)
        UserInfo.setMinimumSize(QtCore.QSize(0, 64))
        UserInfo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        UserInfo.setWindowTitle("")
        UserInfo.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(UserInfo)
        self.gridLayout.setObjectName("gridLayout")
        self.rb_select = RadioButton(UserInfo)
        self.rb_select.setMaximumSize(QtCore.QSize(32, 24))
        self.rb_select.setText("")
        self.rb_select.setObjectName("rb_select")
        self.gridLayout.addWidget(self.rb_select, 0, 0, 1, 1)
        self.l_head = PixmapLabel(UserInfo)
        self.l_head.setText("")
        self.l_head.setObjectName("l_head")
        self.gridLayout.addWidget(self.l_head, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.l_type = SubtitleLabel(UserInfo)
        self.l_type.setText("")
        self.l_type.setObjectName("l_type")
        self.gridLayout_2.addWidget(self.l_type, 1, 0, 1, 1)
        self.l_mode = SubtitleLabel(UserInfo)
        self.l_mode.setText("")
        self.l_mode.setObjectName("l_mode")
        self.gridLayout_2.addWidget(self.l_mode, 1, 1, 1, 1)
        self.l_username = TitleLabel(UserInfo)
        self.l_username.setText("")
        self.l_username.setObjectName("l_username")
        self.gridLayout_2.addWidget(self.l_username, 0, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 2, 1, 1)
        self.pb_refresh = PushButton(UserInfo)
        self.pb_refresh.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pb_refresh.setObjectName("pb_refresh")
        self.gridLayout.addWidget(self.pb_refresh, 0, 4, 1, 1)
        self.pb_del = PushButton(UserInfo)
        self.pb_del.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pb_del.setObjectName("pb_del")
        self.gridLayout.addWidget(self.pb_del, 0, 5, 1, 1)

        self.retranslateUi(UserInfo)
        QtCore.QMetaObject.connectSlotsByName(UserInfo)

    def retranslateUi(self, UserInfo):
        _translate = QtCore.QCoreApplication.translate
        self.pb_refresh.setText(_translate("UserInfo", "刷新"))
        self.pb_del.setText(_translate("UserInfo", "删除"))
from qfluentwidgets import PixmapLabel, PushButton, RadioButton, SubtitleLabel, TitleLabel
