# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Ui\AllHelp\CustomHelp.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomHelp(object):
    def setupUi(self, CustomHelp):
        CustomHelp.setObjectName("CustomHelp")
        CustomHelp.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(CustomHelp)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(CustomHelp)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(CustomHelp)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 980, 580))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pb_lookup = QtWidgets.QPushButton(self.groupBox)
        self.pb_lookup.setObjectName("pb_lookup")
        self.gridLayout_2.addWidget(self.pb_lookup, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)

        self.retranslateUi(CustomHelp)
        QtCore.QMetaObject.connectSlotsByName(CustomHelp)

    def retranslateUi(self, CustomHelp):
        _translate = QtCore.QCoreApplication.translate
        CustomHelp.setWindowTitle(_translate("CustomHelp", "自定义帮助"))
        self.label_3.setText(_translate("CustomHelp", "该界面还需完善"))
        self.groupBox.setTitle(_translate("CustomHelp", "做法"))
        self.pb_lookup.setText(_translate("CustomHelp", "查看\"编写规范\""))
        self.label.setText(_translate("CustomHelp", "将自定义的帮助界面放入FMCL/Help中即可，编写规范与下面帮助中的\"编写规范\"相同"))
