# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Ui\AllHelp\CustomFunction.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomFunction(object):
    def setupUi(self, CustomFunction):
        CustomFunction.setObjectName("CustomFunction")
        CustomFunction.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(CustomFunction)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(CustomFunction)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(CustomFunction)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 980, 580))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)

        self.retranslateUi(CustomFunction)
        QtCore.QMetaObject.connectSlotsByName(CustomFunction)

    def retranslateUi(self, CustomFunction):
        _translate = QtCore.QCoreApplication.translate
        CustomFunction.setWindowTitle(_translate("CustomFunction", "自定义功能"))
        self.label.setText(_translate("CustomFunction", "该界面还需完善"))
        self.groupBox.setTitle(_translate("CustomFunction", "做法"))
        self.label_2.setText(_translate("CustomFunction", "将对应的python文件放入FMCL/Function中"))
        self.groupBox_2.setTitle(_translate("CustomFunction", "注意事项"))
        self.label_4.setText(_translate("CustomFunction", "\"name\"即该功能的名字,用户会看到,\"mainclass\"是这个功能的主类"))
        self.label_3.setText(_translate("CustomFunction", "对应的python文件中必须有config字典变量，其含有\"name\",\"mainclass\"键"))
        self.label_5.setText(_translate("CustomFunction", "主类中必须含有show方法,启动功能时将调用它"))
