# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Ui\AllHelp\CustomTranslate.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomTranslate(object):
    def setupUi(self, CustomTranslate):
        CustomTranslate.setObjectName("CustomTranslate")
        CustomTranslate.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(CustomTranslate)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(CustomTranslate)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(CustomTranslate)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 980, 580))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)

        self.retranslateUi(CustomTranslate)
        QtCore.QMetaObject.connectSlotsByName(CustomTranslate)

    def retranslateUi(self, CustomTranslate):
        _translate = QtCore.QCoreApplication.translate
        CustomTranslate.setWindowTitle(_translate("CustomTranslate", "自定义翻译"))
        self.label.setText(_translate("CustomTranslate", "该界面还需完善"))
        self.groupBox.setTitle(_translate("CustomTranslate", "做法"))
        self.label_2.setText(_translate("CustomTranslate", "将翻译文件放入FMCL/Language即可"))
        self.groupBox_2.setTitle(_translate("CustomTranslate", "注意事项"))
        self.label_4.setText(_translate("CustomTranslate", "将内容以 \"原内容\":\"翻译内容\" 的形式 写入文件中的translate字典中"))
        self.label_6.setText(_translate("CustomTranslate", "必须在文件中写config字典，其中含有\"display_name\"键"))
        self.label_5.setText(_translate("CustomTranslate", "所有的翻译文件均为python源代码"))
        self.label_3.setText(_translate("CustomTranslate", "添加的语言可以与现有语言重合，可以通过这种方式拓展当前已有的语言"))
        self.label_7.setText(_translate("CustomTranslate", "\"display_name\"就是将要显示在设置中的内容"))
