# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Ui\AllHelp\JoinTranslate.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JoinTranslate(object):
    def setupUi(self, JoinTranslate):
        JoinTranslate.setObjectName("JoinTranslate")
        JoinTranslate.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(JoinTranslate)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(JoinTranslate)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(JoinTranslate)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 980, 580))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pb_lookup = QtWidgets.QPushButton(self.groupBox)
        self.pb_lookup.setObjectName("pb_lookup")
        self.gridLayout_3.addWidget(self.pb_lookup, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)

        self.retranslateUi(JoinTranslate)
        QtCore.QMetaObject.connectSlotsByName(JoinTranslate)

    def retranslateUi(self, JoinTranslate):
        _translate = QtCore.QCoreApplication.translate
        JoinTranslate.setWindowTitle(_translate("JoinTranslate", "参与翻译"))
        self.label.setText(_translate("JoinTranslate", "该界面还需完善"))
        self.groupBox.setTitle(_translate("JoinTranslate", "如何参与"))
        self.pb_lookup.setText(_translate("JoinTranslate", "查看\"如何参与\""))
        self.label_2.setText(_translate("JoinTranslate", "方法与下面帮助中的\"如何参与\"相同"))
        self.groupBox_2.setTitle(_translate("JoinTranslate", "编写规范"))
        self.label_3.setText(_translate("JoinTranslate", "将内容以 \"原内容\":\"翻译内容\" 的形式 写入文件中的translate字典中,然后将translate这个变量加入到Translate/__init__.py中的language_map的值中"))
        self.label_4.setText(_translate("JoinTranslate", "language_map的键和all_languages中的元素一一对应，启动器将会将这里面的内容显示到\"设置\"中"))
        self.label_5.setText(_translate("JoinTranslate", "原内容参照Translate/English.py"))
        self.label_6.setText(_translate("JoinTranslate", "所有的翻译文件均为python源代码"))
