# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Ui\Help\AllHelp\JoinWriteHelp.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JoinWriteHelp(object):
    def setupUi(self, JoinWriteHelp):
        JoinWriteHelp.setObjectName("JoinWriteHelp")
        JoinWriteHelp.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(JoinWriteHelp)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(JoinWriteHelp)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 980, 580))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(JoinWriteHelp)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)

        self.retranslateUi(JoinWriteHelp)
        QtCore.QMetaObject.connectSlotsByName(JoinWriteHelp)

    def retranslateUi(self, JoinWriteHelp):
        _translate = QtCore.QCoreApplication.translate
        JoinWriteHelp.setWindowTitle(_translate("JoinWriteHelp", "参与完善帮助"))
        self.groupBox_2.setTitle(_translate("JoinWriteHelp", "编写规范"))
        self.label_2.setText(_translate("JoinWriteHelp", "尽量在Ui/Help/AllHelp里编写新的界面，如果要将界面展示到帮助界面中，请将对应的模块添加到Ui/Help/AllHelp/__init__.py中的allhelp变量中"))
        self.label_3.setText(_translate("JoinWriteHelp", "编写的界面模块必须包含config字典变量，其含有\"type\",\"title\",\"description\",\"mainclass\"键"))
        self.label_6.setText(_translate("JoinWriteHelp", "界面中所用的资源需放到Resources文件中，写入Resources/Resources.qrc文件，并将该资源文件生成到__init__.py"))
        self.groupBox.setTitle(_translate("JoinWriteHelp", "如何参与"))
        self.label.setText(_translate("JoinWriteHelp", "首先注册并登录一个Github账号，然后通过“关于”界面中的“打开源码网址”进入FMCL存储库，点击页面又上角Fork建立分支"))
        self.groupBox_3.setTitle(_translate("JoinWriteHelp", "概述"))
        self.label_4.setText(_translate("JoinWriteHelp", "该界面作为第一个帮助子界面，不仅仅为了测试代码，还是为了让用户参与到完善中"))
        self.label_5.setText(_translate("JoinWriteHelp", "该界面还需完善"))
