# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Ui\CreateUser\Microsoft.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Microsoft(object):
    def setupUi(self, Microsoft):
        Microsoft.setObjectName("Microsoft")
        Microsoft.resize(1000, 618)

        self.retranslateUi(Microsoft)
        QtCore.QMetaObject.connectSlotsByName(Microsoft)

    def retranslateUi(self, Microsoft):
        _translate = QtCore.QCoreApplication.translate
        Microsoft.setWindowTitle(_translate("Microsoft", "微软登录"))
