# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\王永健\PCG\FMCL\Ui\DownloadManager\DownloadManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DownloadManager(object):
    def setupUi(self, DownloadManager):
        DownloadManager.setObjectName("DownloadManager")
        DownloadManager.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(DownloadManager)
        self.gridLayout.setObjectName("gridLayout")
        self.lw_tasks = QtWidgets.QListWidget(DownloadManager)
        self.lw_tasks.setObjectName("lw_tasks")
        self.gridLayout.addWidget(self.lw_tasks, 0, 0, 1, 1)

        self.retranslateUi(DownloadManager)
        QtCore.QMetaObject.connectSlotsByName(DownloadManager)

    def retranslateUi(self, DownloadManager):
        _translate = QtCore.QCoreApplication.translate
        DownloadManager.setWindowTitle(_translate("DownloadManager", "下载管理"))
